/**************************************************************************/
/*  data_gen_auto.h                                                       */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#pragma once
// GENERATED by gds2cpp from res://Data.gd -- do not edit; regenerate.
#include "core/string/string_name.h"
#include "core/variant/variant.h"
class GDScript;
class GDScriptInstance;
class GDScriptFunction;

struct Data_gen {
	typedef Variant (*Fn)(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Fn lookup(const StringName &p_name);
	static GDScriptFunction *g_gf[24]; // per-method GDScriptFunction, for devirt calls
	static void bind(GDScript *p_script); // populate g_gf from the owning script
	static Variant fn__init(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_is_mission_starting(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_clear_all_data(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_load_yaml_data(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_reset_to_default_properties(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_reset_to_default_properties_partial(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_has(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_of(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_ofOr(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_apply(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_clear(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_event(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_listen(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_is_listening(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_onListenerLeftTree(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_unlistenAll(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_unlisten(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_removeListener(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_clearListeners(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_changeBy(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_startCaptialized(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_serialize(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_deserialize(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_should_property_be_saved(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
};
