/**************************************************************************/
/*  data_gen_auto.h                                                       */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#pragma once
// GENERATED by gds2cpp from res://Data.gd -- do not edit; regenerate.
#include "core/string/string_name.h"
#include "core/variant/variant.h"
class GDScriptInstance;
class GDScriptFunction;

struct Data_gen {
	typedef Variant (*Fn)(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Fn lookup(const StringName &p_name);
	static Variant _init(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant is_mission_starting(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant clear_all_data(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant load_yaml_data(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant reset_to_default_properties(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant reset_to_default_properties_partial(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant has(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant of(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant ofOr(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant apply(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant clear(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant event(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant listen(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant is_listening(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant onListenerLeftTree(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant unlistenAll(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant unlisten(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant removeListener(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant clearListeners(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant changeBy(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant startCaptialized(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant serialize(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant deserialize(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant should_property_be_saved(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
};
