/**************************************************************************/
/*  data_gen_auto.cpp                                                     */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// GENERATED by gds2cpp from res://Data.gd -- do not edit; regenerate.
#include "data_gen_auto.h"

#include "core/object/class_db.h"
#include "core/variant/variant_internal.h"
#include "modules/gdscript/gdscript.h"
#include "modules/gdscript/gdscript_function.h"

enum { // g_gf slots
	GF__init = 0,
	GF_is_mission_starting = 1,
	GF_clear_all_data = 2,
	GF_load_yaml_data = 3,
	GF_reset_to_default_properties = 4,
	GF_reset_to_default_properties_partial = 5,
	GF_has = 6,
	GF_of = 7,
	GF_ofOr = 8,
	GF_apply = 9,
	GF_clear = 10,
	GF_event = 11,
	GF_listen = 12,
	GF_is_listening = 13,
	GF_onListenerLeftTree = 14,
	GF_unlistenAll = 15,
	GF_unlisten = 16,
	GF_removeListener = 17,
	GF_clearListeners = 18,
	GF_changeBy = 19,
	GF_startCaptialized = 20,
	GF_serialize = 21,
	GF_deserialize = 22,
	GF_should_property_be_saved = 23,
};
#define GF(m) g_gf[GF_##m]
GDScriptFunction *Data_gen::g_gf[24] = {};
void Data_gen::bind(GDScript *p_script) {
	const HashMap<StringName, GDScriptFunction *> &fns = p_script->get_member_functions();
	if (fns.has(StringName("_init"))) {
		GDScriptFunction *gf = fns[StringName("_init")];
		GF(_init) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn__init);
	}
	if (fns.has(StringName("is_mission_starting"))) {
		GDScriptFunction *gf = fns[StringName("is_mission_starting")];
		GF(is_mission_starting) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_is_mission_starting);
	}
	if (fns.has(StringName("clear_all_data"))) {
		GDScriptFunction *gf = fns[StringName("clear_all_data")];
		GF(clear_all_data) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_clear_all_data);
	}
	if (fns.has(StringName("load_yaml_data"))) {
		GDScriptFunction *gf = fns[StringName("load_yaml_data")];
		GF(load_yaml_data) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_load_yaml_data);
	}
	if (fns.has(StringName("reset_to_default_properties"))) {
		GDScriptFunction *gf = fns[StringName("reset_to_default_properties")];
		GF(reset_to_default_properties) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_reset_to_default_properties);
	}
	if (fns.has(StringName("reset_to_default_properties_partial"))) {
		GDScriptFunction *gf = fns[StringName("reset_to_default_properties_partial")];
		GF(reset_to_default_properties_partial) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_reset_to_default_properties_partial);
	}
	if (fns.has(StringName("has"))) {
		GDScriptFunction *gf = fns[StringName("has")];
		GF(has) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_has);
	}
	if (fns.has(StringName("of"))) {
		GDScriptFunction *gf = fns[StringName("of")];
		GF(of) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_of);
	}
	if (fns.has(StringName("ofOr"))) {
		GDScriptFunction *gf = fns[StringName("ofOr")];
		GF(ofOr) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_ofOr);
	}
	if (fns.has(StringName("apply"))) {
		GDScriptFunction *gf = fns[StringName("apply")];
		GF(apply) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_apply);
	}
	if (fns.has(StringName("clear"))) {
		GDScriptFunction *gf = fns[StringName("clear")];
		GF(clear) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_clear);
	}
	if (fns.has(StringName("event"))) {
		GDScriptFunction *gf = fns[StringName("event")];
		GF(event) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_event);
	}
	if (fns.has(StringName("listen"))) {
		GDScriptFunction *gf = fns[StringName("listen")];
		GF(listen) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_listen);
	}
	if (fns.has(StringName("is_listening"))) {
		GDScriptFunction *gf = fns[StringName("is_listening")];
		GF(is_listening) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_is_listening);
	}
	if (fns.has(StringName("onListenerLeftTree"))) {
		GDScriptFunction *gf = fns[StringName("onListenerLeftTree")];
		GF(onListenerLeftTree) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_onListenerLeftTree);
	}
	if (fns.has(StringName("unlistenAll"))) {
		GDScriptFunction *gf = fns[StringName("unlistenAll")];
		GF(unlistenAll) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_unlistenAll);
	}
	if (fns.has(StringName("unlisten"))) {
		GDScriptFunction *gf = fns[StringName("unlisten")];
		GF(unlisten) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_unlisten);
	}
	if (fns.has(StringName("removeListener"))) {
		GDScriptFunction *gf = fns[StringName("removeListener")];
		GF(removeListener) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_removeListener);
	}
	if (fns.has(StringName("clearListeners"))) {
		GDScriptFunction *gf = fns[StringName("clearListeners")];
		GF(clearListeners) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_clearListeners);
	}
	if (fns.has(StringName("changeBy"))) {
		GDScriptFunction *gf = fns[StringName("changeBy")];
		GF(changeBy) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_changeBy);
	}
	if (fns.has(StringName("startCaptialized"))) {
		GDScriptFunction *gf = fns[StringName("startCaptialized")];
		GF(startCaptialized) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_startCaptialized);
	}
	if (fns.has(StringName("serialize"))) {
		GDScriptFunction *gf = fns[StringName("serialize")];
		GF(serialize) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_serialize);
	}
	if (fns.has(StringName("deserialize"))) {
		GDScriptFunction *gf = fns[StringName("deserialize")];
		GF(deserialize) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_deserialize);
	}
	if (fns.has(StringName("should_property_be_saved"))) {
		GDScriptFunction *gf = fns[StringName("should_property_be_saved")];
		GF(should_property_be_saved) = gf;
		gf->gds2cpp_set_fn(&Data_gen::fn_should_property_be_saved);
	}
}

// --- member slots ---
static constexpr int M_missions = 0;
static constexpr int M_upgrades = 1;
static constexpr int M_manuals = 2;
static constexpr int M_ship_blueprints = 3;
static constexpr int M_ship_systems_blueprints = 4;
static constexpr int M_all_ship_modifiers = 5;
static constexpr int M_shop_products = 6;
static constexpr int M_shop_categories = 7;
static constexpr int M_exams = 8;
static constexpr int M_dialogs = 9;
static constexpr int M_loose_news = 10;
static constexpr int M_default_properties = 11;
static constexpr int M_persistant_properties_matchers = 12;
static constexpr int M_persistant_properties_cache = 13;
static constexpr int M_upgrades_properties = 14;
static constexpr int M_values = 15;
static constexpr int M_temp_event_call_values = 16;
static constexpr int M_listeners = 17;
static constexpr int M_invalids = 18;
static constexpr int M_deserialized = 19;
static constexpr int M_can_override_upgrade_property = 20;

// ----------------------------------------------------------------------------
// func _init():
// 	process_mode = Node.PROCESS_MODE_ALWAYS
// ----------------------------------------------------------------------------
Variant Data_gen::fn__init(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[3];
	enum { GN_process_mode = 0 }; // "process_mode"
	// process_mode = Node.PROCESS_MODE_ALWAYS
	{
		bool valid;
		ClassDB::set_property(inst->get_owner(), gf->get_global_name(GN_process_mode), *gf->gds2cpp_constant_ptr(0), &valid);
	}
	return Variant();
}

// ----------------------------------------------------------------------------
// func is_mission_starting():
// 	return Data.ofOr("mission.state", CONST.MISSION_STATE_STARTING) == CONST.MISSION_STATE_STARTING
// ----------------------------------------------------------------------------
Variant Data_gen::fn_is_mission_starting(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	enum { GN_ofOr = 0 }; // "ofOr"
	Variant &t3 = s[3]; // temp
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	// return Data.ofOr("mission.state", CONST.MISSION_STATE_STARTING) == CONST.MISSION_STATE_STARTING
	*(&t5) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(0), gf->gds2cpp_constant_ptr(1) };
		Variant cret;
		Callable::CallError ce;
		(&t5)->callp(gf->get_global_name(GN_ofOr), ca, 2, cret, ce);
		*(&t4) = cret;
	}
	{
		bool valid;
		Variant::evaluate((Variant::Operator)0, *(&t4), *gf->gds2cpp_constant_ptr(1), *(&t3), valid);
	}
	return *(&t3);
	*(&t5) = Variant();
	*(&t4) = Variant();
	*(&t3) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func clear_all_data():
// 	Data.missions.clear()
// 	Data.upgrades.clear()
// 	Data.manuals.clear()
// 	Data.listeners.clear()
// 	Data.values.clear()
// 	Data.shop_products.clear()
// 	Data.shop_categories.clear()
// 	Data.exams.clear()
// 	Data.default_properties.clear()
// ----------------------------------------------------------------------------
Variant Data_gen::fn_clear_all_data(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	enum { GN_missions = 0,
		GN_upgrades = 1,
		GN_manuals = 2,
		GN_listeners = 3,
		GN_values = 4,
		GN_shop_products = 5,
		GN_shop_categories = 6,
		GN_exams = 7,
		GN_default_properties = 8 }; // "missions", "upgrades", "manuals", "listeners", "values", "shop_products", "shop_categories", "exams", "default_properties"
	Variant &t3 = s[3]; // temp
	Variant &t4 = s[4]; // temp
	// Data.missions.clear()
	*(&t4) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t3) = (&t4)->get_named(gf->get_global_name(GN_missions), valid);
	}
	{
		gf->gds2cpp_builtin_method(0)((&t3), nullptr, 0, (&t4));
	}
	*(&t4) = Variant();
	*(&t3) = Variant();
	// Data.upgrades.clear()
	*(&t3) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t4) = (&t3)->get_named(gf->get_global_name(GN_upgrades), valid);
	}
	{
		gf->gds2cpp_builtin_method(0)((&t4), nullptr, 0, (&t3));
	}
	*(&t3) = Variant();
	*(&t4) = Variant();
	// Data.manuals.clear()
	*(&t4) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t3) = (&t4)->get_named(gf->get_global_name(GN_manuals), valid);
	}
	{
		gf->gds2cpp_builtin_method(1)((&t3), nullptr, 0, (&t4));
	}
	*(&t4) = Variant();
	*(&t3) = Variant();
	// Data.listeners.clear()
	*(&t3) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t4) = (&t3)->get_named(gf->get_global_name(GN_listeners), valid);
	}
	{
		gf->gds2cpp_builtin_method(0)((&t4), nullptr, 0, (&t3));
	}
	*(&t3) = Variant();
	*(&t4) = Variant();
	// Data.values.clear()
	*(&t4) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t3) = (&t4)->get_named(gf->get_global_name(GN_values), valid);
	}
	{
		gf->gds2cpp_builtin_method(0)((&t3), nullptr, 0, (&t4));
	}
	*(&t4) = Variant();
	*(&t3) = Variant();
	// Data.shop_products.clear()
	*(&t3) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t4) = (&t3)->get_named(gf->get_global_name(GN_shop_products), valid);
	}
	{
		gf->gds2cpp_builtin_method(1)((&t4), nullptr, 0, (&t3));
	}
	*(&t3) = Variant();
	*(&t4) = Variant();
	// Data.shop_categories.clear()
	*(&t4) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t3) = (&t4)->get_named(gf->get_global_name(GN_shop_categories), valid);
	}
	{
		gf->gds2cpp_builtin_method(0)((&t3), nullptr, 0, (&t4));
	}
	*(&t4) = Variant();
	*(&t3) = Variant();
	// Data.exams.clear()
	*(&t3) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t4) = (&t3)->get_named(gf->get_global_name(GN_exams), valid);
	}
	{
		gf->gds2cpp_builtin_method(0)((&t4), nullptr, 0, (&t3));
	}
	*(&t3) = Variant();
	*(&t4) = Variant();
	// Data.default_properties.clear()
	*(&t4) = GDScriptLanguage::get_singleton()->get_global_array()[1476];
	{
		bool valid;
		*(&t3) = (&t4)->get_named(gf->get_global_name(GN_default_properties), valid);
	}
	{
		gf->gds2cpp_builtin_method(1)((&t3), nullptr, 0, (&t4));
	}
	*(&t4) = Variant();
	*(&t3) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func load_yaml_data():
// 	can_override_upgrade_property = true
// 	var loader = YamlToDataLoader.new()
// 	loader.run(self,CORE_YAML_FILES)
// 	can_override_upgrade_property = false
// ----------------------------------------------------------------------------
Variant Data_gen::fn_load_yaml_data(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	enum { GN_run = 0 }; // "run"
	Variant &loader = s[3]; // local
	Variant &t4 = s[4]; // temp
	// can_override_upgrade_property = true
	*inst->gds2cpp_member_ptr(M_can_override_upgrade_property) = *gf->gds2cpp_constant_ptr(0);
	// var loader = YamlToDataLoader.new()
	{
		Object *bo = gf->gds2cpp_constant_ptr(1)->operator Object *();
		Callable::CallError ce;
		Variant tr = gf->gds2cpp_method(0)->call(bo, nullptr, 0, ce);
		*(&t4) = tr;
	}
	*(&loader) = *(&t4);
	*(&t4) = Variant();
	// loader.run(self,CORE_YAML_FILES)
	{
		const Variant *ca[] = { (&s[0]), gf->gds2cpp_constant_ptr(2) };
		Variant cret;
		Callable::CallError ce;
		(&loader)->callp(gf->get_global_name(GN_run), ca, 2, cret, ce);
	}
	*(&t4) = Variant();
	// can_override_upgrade_property = false
	*inst->gds2cpp_member_ptr(M_can_override_upgrade_property) = *gf->gds2cpp_constant_ptr(3);
	return Variant();
}

// ----------------------------------------------------------------------------
// func reset_to_default_properties():
// 	values.clear()
// 	listeners.clear()
// 	deserialized = false
// 	can_override_upgrade_property = true
// 	for property_change:PropertyChange in default_properties:
// 		property_change.apply()
// 	can_override_upgrade_property = false
// ----------------------------------------------------------------------------
Variant Data_gen::fn_reset_to_default_properties(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[7];
	enum { GN_apply = 0 }; // "apply"
	Variant &property_change = s[3]; // local
	Variant &_counter_pos = s[4]; // local
	Variant &_container_pos = s[5]; // local
	Variant &t6 = s[6]; // temp
	// values.clear()
	{
		gf->gds2cpp_builtin_method(0)(inst->gds2cpp_member_ptr(M_values), nullptr, 0, (&t6));
	}
	*(&t6) = Variant();
	// listeners.clear()
	{
		gf->gds2cpp_builtin_method(0)(inst->gds2cpp_member_ptr(M_listeners), nullptr, 0, (&t6));
	}
	*(&t6) = Variant();
	// deserialized = false
	*inst->gds2cpp_member_ptr(M_deserialized) = *gf->gds2cpp_constant_ptr(0);
	// can_override_upgrade_property = true
	*inst->gds2cpp_member_ptr(M_can_override_upgrade_property) = *gf->gds2cpp_constant_ptr(1);
	// for property_change:PropertyChange in default_properties:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_default_properties);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L59;
		}
		*(&property_change) = cont->iter_get(*ctr, valid);
	}
	goto L47;
L42:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L59;
		}
		*(&property_change) = cont->iter_get(*ctr, valid);
	}
L47:;
	// property_change.apply()
	{
		Variant cret;
		Callable::CallError ce;
		(&property_change)->callp(gf->get_global_name(GN_apply), nullptr, 0, cret, ce);
	}
	*(&t6) = Variant();
	goto L42;
L59:;
	// can_override_upgrade_property = false
	*inst->gds2cpp_member_ptr(M_can_override_upgrade_property) = *gf->gds2cpp_constant_ptr(0);
	return Variant();
}

// ----------------------------------------------------------------------------
// func reset_to_default_properties_partial(props:Dictionary):
// 	for property_change:PropertyChange in default_properties:
// 		if props.has(property_change.property_key):
// 			property_change.apply()
// ----------------------------------------------------------------------------
Variant Data_gen::fn_reset_to_default_properties_partial(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[10];
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[7], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[8], nullptr, 0, _ce);
	}
	enum { GN_property_key = 0,
		GN_apply = 2 }; // "property_key", "apply"
	Variant &props = s[3]; // arg
	Variant &property_change = s[4]; // local
	Variant &_counter_pos = s[5]; // local
	Variant &_container_pos = s[6]; // local
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	Variant &t9 = s[9]; // temp
	// for property_change:PropertyChange in default_properties:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_default_properties);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L45;
		}
		*(&property_change) = cont->iter_get(*ctr, valid);
	}
	goto L17;
L12:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L45;
		}
		*(&property_change) = cont->iter_get(*ctr, valid);
	}
L17:;
	// if props.has(property_change.property_key):
	{
		bool valid;
		*(&t8) = (&property_change)->get_named(gf->get_global_name(GN_property_key), valid);
	}
	*(&t7) = VariantInternal::get_dictionary((&props))->has(*(&t8)); // native has
	if (!bool(*(&t7))) {
		goto L43;
	}
	// property_change.apply()
	{
		Variant cret;
		Callable::CallError ce;
		(&property_change)->callp(gf->get_global_name(GN_apply), nullptr, 0, cret, ce);
	}
	*(&t9) = Variant();
L43:;
	goto L12;
L45:;
	return Variant();
}

// ----------------------------------------------------------------------------
// func has(property:String) -> bool:
// 	return values.has(property)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_has(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[4], nullptr, 0, _ce);
	}
	Variant &property = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &t4 = s[4]; // temp
	// return values.has(property)
	*(&t4) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_values))->has(*(&property)); // native has
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func of(property_key:String):
// 	# Fast path: keys are stored (and passed) lowercase, so skip the per-access to_lower alloc.
// 	if values.has(property_key):
// 		return values[property_key]
// 	property_key = property_key.to_lower()
// 	if not values.has(property_key):
// 		Log.error("Tried to access unknown data " + property_key)
// 		return null
// 	return values[property_key]
// ----------------------------------------------------------------------------
Variant Data_gen::fn_of(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[4], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[7], nullptr, 0, _ce);
	}
	enum { GN_error = 1 }; // "error"
	Variant &property_key = s[3]; // arg
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	// if values.has(property_key):
	*(&t4) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_values))->has(*(&property_key)); // native has
	if (!bool(*(&t4))) {
		goto L23;
	}
	// return values[property_key]
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_values), (&property_key), (&t5), &valid);
	}
	return *(&t5);
	*(&t5) = Variant();
L23:;
	// property_key = property_key.to_lower()
	{
		gf->gds2cpp_builtin_method(0)((&property_key), nullptr, 0, (&t6));
	}
	*(&property_key) = *(&t6);
	// if not values.has(property_key):
	*(&t7) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_values))->has(*(&property_key)); // native has
	gf->gds2cpp_operator_func(0)((&t7), (&s[2]), (&t4));
	if (!bool(*(&t4))) {
		goto L76;
	}
	// Log.error("Tried to access unknown data " + property_key)
	gf->gds2cpp_operator_func(1)(gf->gds2cpp_constant_ptr(0), (&property_key), (&t6));
	*(&t5) = GDScriptLanguage::get_singleton()->get_global_array()[1475];
	{
		const Variant *ca[] = { (&t6) };
		Variant cret;
		Callable::CallError ce;
		(&t5)->callp(gf->get_global_name(GN_error), ca, 1, cret, ce);
	}
	*(&t8) = Variant();
	*(&t5) = Variant();
	// return null
	return *gf->gds2cpp_constant_ptr(1);
L76:;
	// return values[property_key]
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_values), (&property_key), (&t8), &valid);
	}
	return *(&t8);
	*(&t8) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func ofOr(property:String, default):
// 	if values.has(property):
// 		return values[property]
// 	return values.get(property.to_lower(), default)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_ofOr(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[8];
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[5], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[7], nullptr, 0, _ce);
	}
	Variant &property = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &default_ = *const_cast<Variant *>(p_args[1]); // arg (aliased, no copy)
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	// if values.has(property):
	*(&t5) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_values))->has(*(&property)); // native has
	if (!bool(*(&t5))) {
		goto L23;
	}
	// return values[property]
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_values), (&property), (&t6), &valid);
	}
	return *(&t6);
	*(&t6) = Variant();
L23:;
	// return values.get(property.to_lower(), default)
	{
		gf->gds2cpp_builtin_method(0)((&property), nullptr, 0, (&t7));
	}
	*(&t6) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_values))->get(*(&t7), *(&default_)); // native get
	return *(&t6);
	*(&t6) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func apply(property:String, newValue):
// 	property = property.to_lower()
//
// 	if not can_override_upgrade_property and upgrades_properties.has(property):
// 		Log.warn("Trying to override upgrade-property outside upgrades: %s. Properties used in upgrades are exclusive to them. " % property)
//
// 	var oldValue = values.get(property, null)
// 	#skip if the value was not changed, except for reference types (objects, arrays etc) because in that case the content itself might have changed
// 	if typeof(newValue) < TYPE_OBJECT and typeof(oldValue) == typeof(newValue) and oldValue == newValue:
// 		return
//
// 	values[property] = newValue
// 	invalids.clear()
// 	for l in listeners.get(property, []).duplicate():
// 		if is_instance_valid(l) and l.is_inside_tree():
// 			l.gameDataChanged(property, oldValue, newValue)
// 		else:
// 			invalids.append(l)
// 	for i in invalids:
// 		unlistenAll(i)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_apply(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[18];
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	if (1 < p_argc) {
		s[4] = *p_args[1];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[9], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[10], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[11], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[12], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[15], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[16], nullptr, 0, _ce);
	}
	enum { GN_warn = 1,
		GN_typeof = 3,
		GN_duplicate = 4,
		GN_is_instance_valid = 5,
		GN_is_inside_tree = 6,
		GN_gameDataChanged = 7,
		GN_append = 8 }; // "warn", "typeof", "duplicate", "is_instance_valid", "is_inside_tree", "gameDataChanged", "append"
	Variant &property = s[3]; // arg
	Variant &newValue = s[4]; // arg
	Variant &oldValue = s[5]; // local
	Variant &t6 = s[6]; // temp
	Variant &_counter_pos = s[7]; // local
	Variant &_container_pos = s[8]; // local
	Variant &t9 = s[9]; // temp
	Variant &t10 = s[10]; // temp
	Variant &t11 = s[11]; // temp
	Variant &t12 = s[12]; // temp
	Variant &t13 = s[13]; // temp
	Variant &t14 = s[14]; // temp
	Variant &t15 = s[15]; // temp
	Variant &t16 = s[16]; // temp
	Variant &t17 = s[17]; // temp
	// property = property.to_lower()
	{
		gf->gds2cpp_builtin_method(0)((&property), nullptr, 0, (&t9));
	}
	*(&property) = *(&t9);
	// if not can_override_upgrade_property and upgrades_properties.has(property):
	gf->gds2cpp_operator_func(0)(inst->gds2cpp_member_ptr(M_can_override_upgrade_property), (&s[2]), (&t11));
	if (!bool(*(&t11))) {
		goto L35;
	}
	*(&t12) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_upgrades_properties))->has(*(&property)); // native has
	if (!bool(*(&t12))) {
		goto L35;
	}
	*(&t10) = true;
	goto L37;
L35:;
	*(&t10) = false;
L37:;
	if (!bool(*(&t10))) {
		goto L61;
	}
	// Log.warn("Trying to override upgrade-property outside upgrades: %s. Properties used in upgrades are exclusive to them. " % property)
	gf->gds2cpp_operator_func(1)(gf->gds2cpp_constant_ptr(0), (&property), (&t9));
	*(&t13) = GDScriptLanguage::get_singleton()->get_global_array()[1475];
	{
		const Variant *ca[] = { (&t9) };
		Variant cret;
		Callable::CallError ce;
		(&t13)->callp(gf->get_global_name(GN_warn), ca, 1, cret, ce);
	}
	*(&t14) = Variant();
	*(&t13) = Variant();
L61:;
	// var oldValue = values.get(property, null)
	*(&t14) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_values))->get(*(&property), *gf->gds2cpp_constant_ptr(1)); // native get
	*(&oldValue) = *(&t14);
	*(&t14) = Variant();
	// if typeof(newValue) < TYPE_OBJECT and typeof(oldValue) == typeof(newValue) and oldValue == newValue:
	{
		const Variant *ca[] = { (&newValue) };
		Callable::CallError ce;
		Variant::call_utility_function(gf->get_global_name(GN_typeof), (&t15), ca, 1, ce);
	}
	gf->gds2cpp_operator_func(2)((&t15), gf->gds2cpp_constant_ptr(2), (&t11));
	if (!bool(*(&t11))) {
		goto L116;
	}
	{
		const Variant *ca[] = { (&oldValue) };
		Callable::CallError ce;
		Variant::call_utility_function(gf->get_global_name(GN_typeof), (&t15), ca, 1, ce);
	}
	{
		const Variant *ca[] = { (&newValue) };
		Callable::CallError ce;
		Variant::call_utility_function(gf->get_global_name(GN_typeof), (&t16), ca, 1, ce);
	}
	gf->gds2cpp_operator_func(3)((&t15), (&t16), (&t10));
	if (!bool(*(&t10))) {
		goto L116;
	}
	*(&t12) = true;
	goto L118;
L116:;
	*(&t12) = false;
L118:;
	if (!bool(*(&t12))) {
		goto L137;
	}
	{
		bool valid;
		Variant::evaluate((Variant::Operator)0, *(&oldValue), *(&newValue), *(&t14), valid);
	}
	if (!bool(*(&t14))) {
		goto L137;
	}
	*(&t13) = true;
	goto L139;
L137:;
	*(&t13) = false;
L139:;
	if (!bool(*(&t13))) {
		goto L150;
	}
	*(&t14) = Variant();
	*(&t13) = Variant();
	// return
	return *(&s[2]);
L150:;
	// values[property] = newValue
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)(inst->gds2cpp_member_ptr(M_values), (&property), (&newValue), &valid);
	}
	// invalids.clear()
	{
		gf->gds2cpp_builtin_method(1)(inst->gds2cpp_member_ptr(M_invalids), nullptr, 0, (&t14));
	}
	*(&t14) = Variant();
	// for l in listeners.get(property, []).duplicate():
	{
		Array a;
		a.resize(0);
		Variant *dd = (&t17);
		*dd = Variant();
		*dd = a;
	}
	*(&t14) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_listeners))->get(*(&property), *(&t17)); // native get
	{
		Variant cret;
		Callable::CallError ce;
		(&t14)->callp(gf->get_global_name(GN_duplicate), nullptr, 0, cret, ce);
		*(&t13) = cret;
	}
	*(&_container_pos) = *(&t13);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L269;
		}
		*(&t6) = cont->iter_get(*ctr, valid);
	}
	goto L202;
L197:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L269;
		}
		*(&t6) = cont->iter_get(*ctr, valid);
	}
L202:;
	*(&t17) = Variant();
	*(&t14) = Variant();
	*(&t13) = Variant();
	// if is_instance_valid(l) and l.is_inside_tree():
	{
		const Variant *ca[] = { (&t6) };
		Callable::CallError ce;
		Variant::call_utility_function(gf->get_global_name(GN_is_instance_valid), (&t10), ca, 1, ce);
	}
	if (!bool(*(&t10))) {
		goto L232;
	}
	{
		Variant cret;
		Callable::CallError ce;
		(&t6)->callp(gf->get_global_name(GN_is_inside_tree), nullptr, 0, cret, ce);
		*(&t14) = cret;
	}
	if (!bool(*(&t14))) {
		goto L232;
	}
	*(&t17) = true;
	goto L234;
L232:;
	*(&t17) = false;
L234:;
	if (!bool(*(&t17))) {
		goto L256;
	}
	*(&t14) = Variant();
	*(&t17) = Variant();
	// l.gameDataChanged(property, oldValue, newValue)
	{
		const Variant *ca[] = { (&property), (&oldValue), (&newValue) };
		Variant cret;
		Callable::CallError ce;
		(&t6)->callp(gf->get_global_name(GN_gameDataChanged), ca, 3, cret, ce);
	}
	*(&t13) = Variant();
	goto L267;
L256:;
	// invalids.append(l)
	{
		const Variant *ca[] = { (&t6) };
		Variant cret;
		Callable::CallError ce;
		inst->gds2cpp_member_ptr(M_invalids)->callp(gf->get_global_name(GN_append), ca, 1, cret, ce);
	}
	*(&t14) = Variant();
L267:;
	goto L197;
L269:;
	// for i in invalids:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_invalids);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L299;
		}
		*(&t6) = cont->iter_get(*ctr, valid);
	}
	goto L286;
L281:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L299;
		}
		*(&t6) = cont->iter_get(*ctr, valid);
	}
L286:;
	// unlistenAll(i)
	{
		const Variant *ca[] = { (&t6) };
		Data_gen::fn_unlistenAll(inst, GF(unlistenAll), ca, 1); // devirt unlistenAll
	}
	*(&t17) = Variant();
	goto L281;
L299:;
	return Variant();
}

// ----------------------------------------------------------------------------
// func clear(property:String):
// 	values.erase(property)
// 	listeners.erase(property)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_clear(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	enum { GN_erase = 0 }; // "erase"
	Variant &property = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &t4 = s[4]; // temp
	// values.erase(property)
	{
		const Variant *ca[] = { (&property) };
		Variant cret;
		Callable::CallError ce;
		inst->gds2cpp_member_ptr(M_values)->callp(gf->get_global_name(GN_erase), ca, 1, cret, ce);
	}
	*(&t4) = Variant();
	// listeners.erase(property)
	{
		const Variant *ca[] = { (&property) };
		Variant cret;
		Callable::CallError ce;
		inst->gds2cpp_member_ptr(M_listeners)->callp(gf->get_global_name(GN_erase), ca, 1, cret, ce);
	}
	*(&t4) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func event(eventId:String, oldValue = null, newValue = null):
// 	temp_event_call_values[eventId] = newValue
// 	invalids.clear()
// 	var receivers = listeners.get(eventId, [])
// 	for l in receivers.duplicate():
// 		if is_instance_valid(l) and l.is_inside_tree():
// 			l.gameDataChanged(eventId, oldValue, newValue)
// 		else:
// 			invalids.append(l)
// 	for i in invalids:
// 		unlistenAll(i)
// 	temp_event_call_values.erase(eventId)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_event(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[13];
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	if (1 < p_argc) {
		s[4] = *p_args[1];
	}
	if (2 < p_argc) {
		s[5] = *p_args[2];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[12], nullptr, 0, _ce);
	}
	enum { GN_duplicate = 1,
		GN_is_instance_valid = 2,
		GN_is_inside_tree = 3,
		GN_gameDataChanged = 4,
		GN_append = 5,
		GN_erase = 7 }; // "duplicate", "is_instance_valid", "is_inside_tree", "gameDataChanged", "append", "erase"
	Variant &eventId = s[3]; // arg
	Variant &oldValue = s[4]; // arg
	Variant &newValue = s[5]; // arg
	Variant &receivers = s[6]; // local
	Variant &t7 = s[7]; // temp
	Variant &_counter_pos = s[8]; // local
	Variant &_container_pos = s[9]; // local
	Variant &t10 = s[10]; // temp
	Variant &t11 = s[11]; // temp
	Variant &t12 = s[12]; // temp
	{
		int defarg = (p_argc < 3) ? (3 - p_argc) : 0;
		if (defarg > 2) {
			defarg = 2;
		}
		switch (defarg) {
			case 0:
				goto L7;
			case 1:
				goto L4;
			case 2:
				goto L1;
		}
	}
L1:;
	*(&oldValue) = *gf->gds2cpp_constant_ptr(0);
L4:;
	*(&newValue) = *gf->gds2cpp_constant_ptr(0);
L7:;
	// temp_event_call_values[eventId] = newValue
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)(inst->gds2cpp_member_ptr(M_temp_event_call_values), (&eventId), (&newValue), &valid);
	}
	// invalids.clear()
	{
		gf->gds2cpp_builtin_method(0)(inst->gds2cpp_member_ptr(M_invalids), nullptr, 0, (&t10));
	}
	*(&t10) = Variant();
	// var receivers = listeners.get(eventId, [])
	{
		Array a;
		a.resize(0);
		Variant *dd = (&t11);
		*dd = Variant();
		*dd = a;
	}
	*(&t10) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_listeners))->get(*(&eventId), *(&t11)); // native get
	*(&receivers) = *(&t10);
	*(&t11) = Variant();
	*(&t10) = Variant();
	// for l in receivers.duplicate():
	{
		Variant cret;
		Callable::CallError ce;
		(&receivers)->callp(gf->get_global_name(GN_duplicate), nullptr, 0, cret, ce);
		*(&t11) = cret;
	}
	*(&_container_pos) = *(&t11);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L131;
		}
		*(&t7) = cont->iter_get(*ctr, valid);
	}
	goto L68;
L63:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L131;
		}
		*(&t7) = cont->iter_get(*ctr, valid);
	}
L68:;
	*(&t11) = Variant();
	// if is_instance_valid(l) and l.is_inside_tree():
	{
		const Variant *ca[] = { (&t7) };
		Callable::CallError ce;
		Variant::call_utility_function(gf->get_global_name(GN_is_instance_valid), (&t12), ca, 1, ce);
	}
	if (!bool(*(&t12))) {
		goto L94;
	}
	{
		Variant cret;
		Callable::CallError ce;
		(&t7)->callp(gf->get_global_name(GN_is_inside_tree), nullptr, 0, cret, ce);
		*(&t11) = cret;
	}
	if (!bool(*(&t11))) {
		goto L94;
	}
	*(&t10) = true;
	goto L96;
L94:;
	*(&t10) = false;
L96:;
	if (!bool(*(&t10))) {
		goto L118;
	}
	*(&t11) = Variant();
	*(&t10) = Variant();
	// l.gameDataChanged(eventId, oldValue, newValue)
	{
		const Variant *ca[] = { (&eventId), (&oldValue), (&newValue) };
		Variant cret;
		Callable::CallError ce;
		(&t7)->callp(gf->get_global_name(GN_gameDataChanged), ca, 3, cret, ce);
	}
	*(&t11) = Variant();
	goto L129;
L118:;
	// invalids.append(l)
	{
		const Variant *ca[] = { (&t7) };
		Variant cret;
		Callable::CallError ce;
		inst->gds2cpp_member_ptr(M_invalids)->callp(gf->get_global_name(GN_append), ca, 1, cret, ce);
	}
	*(&t10) = Variant();
L129:;
	goto L63;
L131:;
	// for i in invalids:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_invalids);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L161;
		}
		*(&t7) = cont->iter_get(*ctr, valid);
	}
	goto L148;
L143:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L161;
		}
		*(&t7) = cont->iter_get(*ctr, valid);
	}
L148:;
	// unlistenAll(i)
	{
		const Variant *ca[] = { (&t7) };
		Data_gen::fn_unlistenAll(inst, GF(unlistenAll), ca, 1); // devirt unlistenAll
	}
	*(&t11) = Variant();
	goto L143;
L161:;
	// temp_event_call_values.erase(eventId)
	{
		const Variant *ca[] = { (&eventId) };
		Variant cret;
		Callable::CallError ce;
		inst->gds2cpp_member_ptr(M_temp_event_call_values)->callp(gf->get_global_name(GN_erase), ca, 1, cret, ce);
	}
	*(&t10) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func listen(listener, property:String, immediateCallback:=false, error_on_relisten:= true):
// 	# I commented this out for now, too much stuff in the output...
// 	#print(listener.name + " listen for "+property)
// 	property = property.to_lower()
// 	var list:Array
// 	if listeners.has(property):
// 		list = listeners[property]
// 	else:
// 		list = []
// 		listeners[property] = list
//
// 	if list.has(listener):
// 		if error_on_relisten:
// 			Log.error("adding listener who is already listening", "Data.listen", {"listener":listener, "property":property})
// 		return
// 	list.append(listener)
// 	if immediateCallback and values.has(property):
// 		listener.gameDataChanged(property, null, of(property))
// #		calling with default might be bad, because transient properties are not initialized by gamedata
// #		listener.gameDataChanged(property, default(property), of(property))
// 	if not listener.tree_exiting.is_connected(onListenerLeftTree):
// 		listener.tree_exiting.connect(onListenerLeftTree.bind(listener))
// ----------------------------------------------------------------------------
Variant Data_gen::fn_listen(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[16];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	if (1 < p_argc) {
		s[4] = *p_args[1];
	}
	if (2 < p_argc) {
		s[5] = *p_args[2];
	}
	if (3 < p_argc) {
		s[6] = *p_args[3];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[8], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[9], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[13], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)25, s[15], nullptr, 0, _ce);
	}
	enum { GN_has = 0,
		GN_error = 1,
		GN_append = 2,
		GN_gameDataChanged = 4,
		GN_onListenerLeftTree = 5,
		GN_tree_exiting = 6,
		GN_is_connected = 7,
		GN_bind = 8,
		GN_connect = 9 }; // "has", "error", "append", "gameDataChanged", "onListenerLeftTree", "tree_exiting", "is_connected", "bind", "connect"
	Variant &listener = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &property = s[4]; // arg
	Variant &immediateCallback = s[5]; // arg
	Variant &error_on_relisten = s[6]; // arg
	Variant &list = s[7]; // local
	Variant &t8 = s[8]; // temp
	Variant &t9 = s[9]; // temp
	Variant &t10 = s[10]; // temp
	Variant &t11 = s[11]; // temp
	Variant &t12 = s[12]; // temp
	Variant &t13 = s[13]; // temp
	Variant &t14 = s[14]; // temp
	Variant &t15 = s[15]; // temp
	{
		int defarg = (p_argc < 4) ? (4 - p_argc) : 0;
		if (defarg > 2) {
			defarg = 2;
		}
		switch (defarg) {
			case 0:
				goto L7;
			case 1:
				goto L4;
			case 2:
				goto L1;
		}
	}
L1:;
	*(&immediateCallback) = *gf->gds2cpp_constant_ptr(0);
L4:;
	*(&error_on_relisten) = *gf->gds2cpp_constant_ptr(1);
L7:;
	// property = property.to_lower()
	{
		gf->gds2cpp_builtin_method(0)((&property), nullptr, 0, (&t8));
	}
	*(&property) = *(&t8);
	// var list:Array
	{
		gf->gds2cpp_constructor(0)((&list), nullptr);
	}
	// if listeners.has(property):
	*(&t9) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_listeners))->has(*(&property)); // native has
	if (!bool(*(&t9))) {
		goto L52;
	}
	// list = listeners[property]
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_listeners), (&property), (&t10), &valid);
	}
	{
		Variant *td = (&list);
		const Variant *ts = (&t10);
		Variant::Type vt = (Variant::Type)28;
		if (ts->get_type() != vt && Variant::can_convert_strict(ts->get_type(), vt)) {
			Callable::CallError ce;
			Variant::construct(vt, *td, &ts, 1, ce);
		} else {
			*td = *ts;
		}
	}
	*(&t10) = Variant();
	goto L70;
L52:;
	// list = []
	{
		Array a;
		a.resize(0);
		Variant *dd = (&t10);
		*dd = Variant();
		*dd = a;
	}
	*(&list) = *(&t10);
	*(&t10) = Variant();
	// listeners[property] = list
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)(inst->gds2cpp_member_ptr(M_listeners), (&property), (&list), &valid);
	}
L70:;
	// if list.has(listener):
	{
		const Variant *ca[] = { (&listener) };
		Variant cret;
		Callable::CallError ce;
		(&list)->callp(gf->get_global_name(GN_has), ca, 1, cret, ce);
		*(&t9) = cret;
	}
	if (!bool(*(&t9))) {
		goto L119;
	}
	// if error_on_relisten:
	if (!bool(*(&error_on_relisten))) {
		goto L115;
	}
	// Log.error("adding listener who is already listening", "Data.listen", {"listener":listener, "property":property})
	{
		Dictionary d;
		d[*gf->gds2cpp_constant_ptr(4)] = *(&listener);
		d[*gf->gds2cpp_constant_ptr(5)] = *(&property);
		Variant *dd = (&t10);
		*dd = Variant();
		*dd = d;
	}
	*(&t11) = GDScriptLanguage::get_singleton()->get_global_array()[1475];
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(2), gf->gds2cpp_constant_ptr(3), (&t10) };
		Variant cret;
		Callable::CallError ce;
		(&t11)->callp(gf->get_global_name(GN_error), ca, 3, cret, ce);
	}
	*(&t12) = Variant();
	*(&t11) = Variant();
	*(&t10) = Variant();
L115:;
	// return
	return *(&s[2]);
L119:;
	// list.append(listener)
	{
		const Variant *ca[] = { (&listener) };
		Variant cret;
		Callable::CallError ce;
		(&list)->callp(gf->get_global_name(GN_append), ca, 1, cret, ce);
	}
	*(&t12) = Variant();
	// if immediateCallback and values.has(property):
	if (!bool(*(&immediateCallback))) {
		goto L149;
	}
	*(&t13) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_values))->has(*(&property)); // native has
	if (!bool(*(&t13))) {
		goto L149;
	}
	*(&t9) = true;
	goto L151;
L149:;
	*(&t9) = false;
L151:;
	if (!bool(*(&t9))) {
		goto L176;
	}
	// listener.gameDataChanged(property, null, of(property))
	{
		const Variant *ca[] = { (&property) };
		*(&t11) = Data_gen::fn_of(inst, GF(of), ca, 1); // devirt of
	}
	{
		const Variant *ca[] = { (&property), gf->gds2cpp_constant_ptr(6), (&t11) };
		Variant cret;
		Callable::CallError ce;
		(&listener)->callp(gf->get_global_name(GN_gameDataChanged), ca, 3, cret, ce);
	}
	*(&t10) = Variant();
	*(&t11) = Variant();
L176:;
	// if not listener.tree_exiting.is_connected(onListenerLeftTree):
	{
		bool valid;
		*(&t11) = (&s[0])->get_named(gf->get_global_name(GN_onListenerLeftTree), valid);
	}
	{
		bool valid;
		*(&t14) = (&listener)->get_named(gf->get_global_name(GN_tree_exiting), valid);
	}
	{
		const Variant *ca[] = { (&t11) };
		Variant cret;
		Callable::CallError ce;
		(&t14)->callp(gf->get_global_name(GN_is_connected), ca, 1, cret, ce);
		*(&t10) = cret;
	}
	{
		bool valid;
		Variant::evaluate((Variant::Operator)23, *(&t10), *(&s[2]), *(&t12), valid);
	}
	if (!bool(*(&t12))) {
		goto L243;
	}
	*(&t14) = Variant();
	*(&t11) = Variant();
	*(&t10) = Variant();
	*(&t12) = Variant();
	// listener.tree_exiting.connect(onListenerLeftTree.bind(listener))
	{
		bool valid;
		*(&t14) = (&s[0])->get_named(gf->get_global_name(GN_onListenerLeftTree), valid);
	}
	{
		const Variant *ca[] = { (&listener) };
		Variant cret;
		Callable::CallError ce;
		(&t14)->callp(gf->get_global_name(GN_bind), ca, 1, cret, ce);
		*(&t15) = cret;
	}
	{
		bool valid;
		*(&t11) = (&listener)->get_named(gf->get_global_name(GN_tree_exiting), valid);
	}
	{
		const Variant *ca[] = { (&t15) };
		Variant cret;
		Callable::CallError ce;
		(&t11)->callp(gf->get_global_name(GN_connect), ca, 1, cret, ce);
	}
	*(&t14) = Variant();
	*(&t10) = Variant();
	*(&t11) = Variant();
L243:;
	return Variant();
}

// ----------------------------------------------------------------------------
// func is_listening(listener, property) -> bool:
// 	property = property.to_lower()
// 	if not listeners.has(property):
// 		return false
// 	return listeners[property].has(listener)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_is_listening(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	if (1 < p_argc) {
		s[4] = *p_args[1];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[7], nullptr, 0, _ce);
	}
	enum { GN_to_lower = 0,
		GN_has = 1 }; // "to_lower", "has"
	Variant &listener = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &property = s[4]; // arg
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	// property = property.to_lower()
	{
		Variant cret;
		Callable::CallError ce;
		(&property)->callp(gf->get_global_name(GN_to_lower), nullptr, 0, cret, ce);
		*(&t5) = cret;
	}
	*(&property) = *(&t5);
	*(&t5) = Variant();
	// if not listeners.has(property):
	*(&t7) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_listeners))->has(*(&property)); // native has
	gf->gds2cpp_operator_func(0)((&t7), (&s[2]), (&t6));
	if (!bool(*(&t6))) {
		goto L34;
	}
	// return false
	return *gf->gds2cpp_constant_ptr(0);
L34:;
	// return listeners[property].has(listener)
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_listeners), (&property), (&t8), &valid);
	}
	{
		const Variant *ca[] = { (&listener) };
		Variant cret;
		Callable::CallError ce;
		(&t8)->callp(gf->get_global_name(GN_has), ca, 1, cret, ce);
		*(&t5) = cret;
	}
	{
		const Variant *rr = (&t5);
		Variant::Type rt = (Variant::Type)1;
		if (rr->get_type() != rt) {
			Callable::CallError ce;
			Variant rv;
			if (Variant::can_convert_strict(rr->get_type(), rt)) {
				Variant::construct(rt, rv, &rr, 1, ce);
			} else {
				Variant::construct(rt, rv, nullptr, 0, ce);
			}
			return rv;
		}
		return *rr;
	}
	*(&t8) = Variant();
	*(&t5) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func onListenerLeftTree(listener):
// 	#don't unsubscribe for simple reparenting
// 	if listener.is_queued_for_deletion():
// 		for prop in listeners:
// 			call_deferred("removeListener", listeners[prop], listener)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_onListenerLeftTree(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	enum { GN_is_queued_for_deletion = 0 }; // "is_queued_for_deletion"
	Variant &listener = s[3]; // arg
	Variant &prop = s[4]; // local
	Variant &_counter_pos = s[5]; // local
	Variant &_container_pos = s[6]; // local
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	// if listener.is_queued_for_deletion():
	{
		Variant cret;
		Callable::CallError ce;
		(&listener)->callp(gf->get_global_name(GN_is_queued_for_deletion), nullptr, 0, cret, ce);
		*(&t7) = cret;
	}
	if (!bool(*(&t7))) {
		goto L52;
	}
	*(&t7) = Variant();
	// for prop in listeners:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_listeners);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L52;
		}
		*(&prop) = cont->iter_get(*ctr, valid);
	}
	goto L30;
L25:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L52;
		}
		*(&prop) = cont->iter_get(*ctr, valid);
	}
L30:;
	// call_deferred("removeListener", listeners[prop], listener)
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_listeners), (&prop), (&t7), &valid);
	}
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(0), (&t7), (&listener) };
		Object *bo = (&s[0])->operator Object *();
		Callable::CallError ce;
		Variant tr = gf->gds2cpp_method(0)->call(bo, ca, 3, ce);
	}
	*(&t8) = Variant();
	*(&t7) = Variant();
	goto L25;
L52:;
	return Variant();
}

// ----------------------------------------------------------------------------
// func unlistenAll(listener):
// 	for prop in listeners:
// 		removeListener(listeners[prop], listener)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_unlistenAll(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	Variant &listener = s[3]; // arg
	Variant &prop = s[4]; // local
	Variant &_counter_pos = s[5]; // local
	Variant &_container_pos = s[6]; // local
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	// for prop in listeners:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_listeners);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L38;
		}
		*(&prop) = cont->iter_get(*ctr, valid);
	}
	goto L17;
L12:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L38;
		}
		*(&prop) = cont->iter_get(*ctr, valid);
	}
L17:;
	// removeListener(listeners[prop], listener)
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_listeners), (&prop), (&t7), &valid);
	}
	{
		const Variant *ca[] = { (&t7), (&listener) };
		Data_gen::fn_removeListener(inst, GF(removeListener), ca, 2); // devirt removeListener
	}
	*(&t8) = Variant();
	*(&t7) = Variant();
	goto L12;
L38:;
	return Variant();
}

// ----------------------------------------------------------------------------
// func unlisten(listener, property:String):
// #	print(listener.name + " unlisten for " + property)
// 	property = property.to_lower()
// 	var list:Array = listeners.get(property, [])
// 	if not list.has(listener):
// 		Log.error("removing listener who is not listening", "Data.unlisten", {"listener":listener, "property":property})
// 		return
// 	list.erase(listener)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_unlisten(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[12];
	if (1 < p_argc) {
		s[4] = *p_args[1];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[9], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[10], nullptr, 0, _ce);
	}
	enum { GN_has = 1,
		GN_error = 2,
		GN_erase = 3 }; // "has", "error", "erase"
	Variant &listener = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &property = s[4]; // arg
	Variant &list = s[5]; // local
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	Variant &t9 = s[9]; // temp
	Variant &t10 = s[10]; // temp
	Variant &t11 = s[11]; // temp
	// property = property.to_lower()
	{
		gf->gds2cpp_builtin_method(0)((&property), nullptr, 0, (&t6));
	}
	*(&property) = *(&t6);
	// var list:Array = listeners.get(property, [])
	{
		Array a;
		a.resize(0);
		Variant *dd = (&t8);
		*dd = Variant();
		*dd = a;
	}
	*(&t7) = VariantInternal::get_dictionary(inst->gds2cpp_member_ptr(M_listeners))->get(*(&property), *(&t8)); // native get
	{
		Variant *td = (&list);
		const Variant *ts = (&t7);
		Variant::Type vt = (Variant::Type)28;
		if (ts->get_type() != vt && Variant::can_convert_strict(ts->get_type(), vt)) {
			Callable::CallError ce;
			Variant::construct(vt, *td, &ts, 1, ce);
		} else {
			*td = *ts;
		}
	}
	*(&t8) = Variant();
	*(&t7) = Variant();
	// if not list.has(listener):
	{
		const Variant *ca[] = { (&listener) };
		Variant cret;
		Callable::CallError ce;
		(&list)->callp(gf->get_global_name(GN_has), ca, 1, cret, ce);
		*(&t10) = cret;
	}
	gf->gds2cpp_operator_func(0)((&t10), (&s[2]), (&t9));
	if (!bool(*(&t9))) {
		goto L82;
	}
	// Log.error("removing listener who is not listening", "Data.unlisten", {"listener":listener, "property":property})
	{
		Dictionary d;
		d[*gf->gds2cpp_constant_ptr(2)] = *(&listener);
		d[*gf->gds2cpp_constant_ptr(3)] = *(&property);
		Variant *dd = (&t8);
		*dd = Variant();
		*dd = d;
	}
	*(&t7) = GDScriptLanguage::get_singleton()->get_global_array()[1475];
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(0), gf->gds2cpp_constant_ptr(1), (&t8) };
		Variant cret;
		Callable::CallError ce;
		(&t7)->callp(gf->get_global_name(GN_error), ca, 3, cret, ce);
	}
	*(&t11) = Variant();
	*(&t7) = Variant();
	*(&t8) = Variant();
	// return
	return *(&s[2]);
L82:;
	// list.erase(listener)
	{
		const Variant *ca[] = { (&listener) };
		Variant cret;
		Callable::CallError ce;
		(&list)->callp(gf->get_global_name(GN_erase), ca, 1, cret, ce);
	}
	*(&t11) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func removeListener(list, listener):
// 	list.erase(listener)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_removeListener(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	enum { GN_erase = 0 }; // "erase"
	Variant &list = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &listener = *const_cast<Variant *>(p_args[1]); // arg (aliased, no copy)
	Variant &t5 = s[5]; // temp
	// list.erase(listener)
	{
		const Variant *ca[] = { (&listener) };
		Variant cret;
		Callable::CallError ce;
		(&list)->callp(gf->get_global_name(GN_erase), ca, 1, cret, ce);
	}
	*(&t5) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func clearListeners():
// 	listeners.clear()
// ----------------------------------------------------------------------------
Variant Data_gen::fn_clearListeners(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	Variant &t3 = s[3]; // temp
	// listeners.clear()
	{
		gf->gds2cpp_builtin_method(0)(inst->gds2cpp_member_ptr(M_listeners), nullptr, 0, (&t3));
	}
	*(&t3) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func changeBy(property:String, change):
// 	return apply(property, change + ofOr(property,0))
// ----------------------------------------------------------------------------
Variant Data_gen::fn_changeBy(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[8];
	Variant &property = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &change = *const_cast<Variant *>(p_args[1]); // arg (aliased, no copy)
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	// return apply(property, change + ofOr(property,0))
	{
		const Variant *ca[] = { (&property), gf->gds2cpp_constant_ptr(0) };
		*(&t7) = Data_gen::fn_ofOr(inst, GF(ofOr), ca, 2); // devirt ofOr
	}
	{
		bool valid;
		Variant::evaluate((Variant::Operator)6, *(&change), *(&t7), *(&t6), valid);
	}
	{
		const Variant *ca[] = { (&property), (&t6) };
		*(&t5) = Data_gen::fn_apply(inst, GF(apply), ca, 2); // devirt apply
	}
	return *(&t5);
	*(&t7) = Variant();
	*(&t6) = Variant();
	*(&t5) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func startCaptialized(s:String):
// 	return s.substr(0,1).to_upper() + s.substr(1,s.length() - 1)
// ----------------------------------------------------------------------------
Variant Data_gen::fn_startCaptialized(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[4], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[5], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[7], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[8], nullptr, 0, _ce);
	}
	Variant &s_ = *const_cast<Variant *>(p_args[0]); // arg (aliased, no copy)
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	// return s.substr(0,1).to_upper() + s.substr(1,s.length() - 1)
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(0), gf->gds2cpp_constant_ptr(1) };
		gf->gds2cpp_builtin_method(0)((&s_), ca, 2, (&t6));
	}
	{
		gf->gds2cpp_builtin_method(1)((&t6), nullptr, 0, (&t5));
	}
	{
		gf->gds2cpp_builtin_method(2)((&s_), nullptr, 0, (&t8));
	}
	gf->gds2cpp_operator_func(0)((&t8), gf->gds2cpp_constant_ptr(1), (&t7));
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(1), (&t7) };
		gf->gds2cpp_builtin_method(0)((&s_), ca, 2, (&t6));
	}
	gf->gds2cpp_operator_func(1)((&t5), (&t6), (&t4));
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func serialize() -> Dictionary:
// 	var saved := {}
// 	for x in values:
// 		if should_property_be_saved(x):
// 			saved[x] = values[x]
// 	return saved
// ----------------------------------------------------------------------------
Variant Data_gen::fn_serialize(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[8];
	Variant &saved = s[3]; // local
	Variant &x = s[4]; // local
	Variant &_counter_pos = s[5]; // local
	Variant &_container_pos = s[6]; // local
	Variant &t7 = s[7]; // temp
	// var saved := {}
	{
		Dictionary d;
		Variant *dd = (&t7);
		*dd = Variant();
		*dd = d;
	}
	*(&saved) = *(&t7);
	*(&t7) = Variant();
	// for x in values:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_values);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L58;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
	goto L28;
L23:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L58;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
L28:;
	// if should_property_be_saved(x):
	{
		const Variant *ca[] = { (&x) };
		*(&t7) = Data_gen::fn_should_property_be_saved(inst, GF(should_property_be_saved), ca, 1); // devirt should_property_be_saved
	}
	if (!bool(*(&t7))) {
		goto L56;
	}
	*(&t7) = Variant();
	// saved[x] = values[x]
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)(inst->gds2cpp_member_ptr(M_values), (&x), (&t7), &valid);
	}
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)((&saved), (&x), (&t7), &valid);
	}
	*(&t7) = Variant();
L56:;
	goto L23;
L58:;
	// return saved
	return *(&saved);
	return Variant();
}

// ----------------------------------------------------------------------------
// func deserialize(data:Dictionary):
// 	deserialized = true
// 	for d in data:
// 		values[d] = data[d]
// ----------------------------------------------------------------------------
Variant Data_gen::fn_deserialize(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[8];
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	Variant &data = s[3]; // arg
	Variant &d_ = s[4]; // local
	Variant &_counter_pos = s[5]; // local
	Variant &_container_pos = s[6]; // local
	Variant &t7 = s[7]; // temp
	// deserialized = true
	*inst->gds2cpp_member_ptr(M_deserialized) = *gf->gds2cpp_constant_ptr(0);
	// for d in data:
	*(&_container_pos) = *(&data);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L38;
		}
		*(&d_) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L38;
		}
		*(&d_) = cont->iter_get(*ctr, valid);
	}
L22:;
	// values[d] = data[d]
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)((&data), (&d_), (&t7), &valid);
	}
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)(inst->gds2cpp_member_ptr(M_values), (&d_), (&t7), &valid);
	}
	*(&t7) = Variant();
	goto L17;
L38:;
	return Variant();
}

// ----------------------------------------------------------------------------
// func should_property_be_saved(prop):
// 	var v = persistant_properties_cache.get(prop)
// 	if v != null:
// 		return v
//
// 	for x : RegEx in persistant_properties_matchers:
// 		var m = x.search(prop)
// 		if m != null:
// 			persistant_properties_cache[prop] = true
// 			return true
//
// 	persistant_properties_cache[prop] = false
// 	return false
// ----------------------------------------------------------------------------
Variant Data_gen::fn_should_property_be_saved(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[12];
	if (0 < p_argc) {
		s[3] = *p_args[0];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[11], nullptr, 0, _ce);
	}
	enum { GN_get = 0 }; // "get"
	Variant &prop = s[3]; // arg
	Variant &v = s[4]; // local
	Variant &x = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &_iterator_temp = s[8]; // local
	Variant &m = s[9]; // local
	Variant &t10 = s[10]; // temp
	Variant &t11 = s[11]; // temp
	// var v = persistant_properties_cache.get(prop)
	{
		const Variant *ca[] = { (&prop) };
		Variant cret;
		Callable::CallError ce;
		inst->gds2cpp_member_ptr(M_persistant_properties_cache)->callp(gf->get_global_name(GN_get), ca, 1, cret, ce);
		*(&t10) = cret;
	}
	*(&v) = *(&t10);
	*(&t10) = Variant();
	// if v != null:
	{
		bool valid;
		Variant::evaluate((Variant::Operator)1, *(&v), *gf->gds2cpp_constant_ptr(0), *(&t11), valid);
	}
	if (!bool(*(&t11))) {
		goto L32;
	}
	// return v
	return *(&v);
L32:;
	// for x : RegEx in persistant_properties_matchers:
	*(&_container_pos) = *inst->gds2cpp_member_ptr(M_persistant_properties_matchers);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L96;
		}
		*(&_iterator_temp) = cont->iter_get(*ctr, valid);
	}
	goto L49;
L44:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L96;
		}
		*(&_iterator_temp) = cont->iter_get(*ctr, valid);
	}
L49:;
	*(&x) = *(&_iterator_temp);
	*(&_iterator_temp) = Variant();
	// var m = x.search(prop)
	{
		const Variant *ca[] = { (&prop) };
		Object *bo = (&x)->operator Object *();
		Callable::CallError ce;
		Variant tr = gf->gds2cpp_method(0)->call(bo, ca, 1, ce);
		*(&t10) = tr;
	}
	*(&m) = *(&t10);
	*(&t10) = Variant();
	// if m != null:
	{
		bool valid;
		Variant::evaluate((Variant::Operator)1, *(&m), *gf->gds2cpp_constant_ptr(0), *(&t11), valid);
	}
	if (!bool(*(&t11))) {
		goto L94;
	}
	// persistant_properties_cache[prop] = true
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)(inst->gds2cpp_member_ptr(M_persistant_properties_cache), (&prop), gf->gds2cpp_constant_ptr(2), &valid);
	}
	// return true
	return *gf->gds2cpp_constant_ptr(2);
L94:;
	goto L44;
L96:;
	*(&m) = Variant();
	// persistant_properties_cache[prop] = false
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)(inst->gds2cpp_member_ptr(M_persistant_properties_cache), (&prop), gf->gds2cpp_constant_ptr(3), &valid);
	}
	// return false
	return *gf->gds2cpp_constant_ptr(3);
	return Variant();
}

Data_gen::Fn Data_gen::lookup(const StringName &p_name) {
	if (p_name == StringName("_init")) {
		return &Data_gen::fn__init;
	}
	if (p_name == StringName("is_mission_starting")) {
		return &Data_gen::fn_is_mission_starting;
	}
	if (p_name == StringName("clear_all_data")) {
		return &Data_gen::fn_clear_all_data;
	}
	if (p_name == StringName("load_yaml_data")) {
		return &Data_gen::fn_load_yaml_data;
	}
	if (p_name == StringName("reset_to_default_properties")) {
		return &Data_gen::fn_reset_to_default_properties;
	}
	if (p_name == StringName("reset_to_default_properties_partial")) {
		return &Data_gen::fn_reset_to_default_properties_partial;
	}
	if (p_name == StringName("has")) {
		return &Data_gen::fn_has;
	}
	if (p_name == StringName("of")) {
		return &Data_gen::fn_of;
	}
	if (p_name == StringName("ofOr")) {
		return &Data_gen::fn_ofOr;
	}
	if (p_name == StringName("apply")) {
		return &Data_gen::fn_apply;
	}
	if (p_name == StringName("clear")) {
		return &Data_gen::fn_clear;
	}
	if (p_name == StringName("event")) {
		return &Data_gen::fn_event;
	}
	if (p_name == StringName("listen")) {
		return &Data_gen::fn_listen;
	}
	if (p_name == StringName("is_listening")) {
		return &Data_gen::fn_is_listening;
	}
	if (p_name == StringName("onListenerLeftTree")) {
		return &Data_gen::fn_onListenerLeftTree;
	}
	if (p_name == StringName("unlistenAll")) {
		return &Data_gen::fn_unlistenAll;
	}
	if (p_name == StringName("unlisten")) {
		return &Data_gen::fn_unlisten;
	}
	if (p_name == StringName("removeListener")) {
		return &Data_gen::fn_removeListener;
	}
	if (p_name == StringName("clearListeners")) {
		return &Data_gen::fn_clearListeners;
	}
	if (p_name == StringName("changeBy")) {
		return &Data_gen::fn_changeBy;
	}
	if (p_name == StringName("startCaptialized")) {
		return &Data_gen::fn_startCaptialized;
	}
	if (p_name == StringName("serialize")) {
		return &Data_gen::fn_serialize;
	}
	if (p_name == StringName("deserialize")) {
		return &Data_gen::fn_deserialize;
	}
	if (p_name == StringName("should_property_be_saved")) {
		return &Data_gen::fn_should_property_be_saved;
	}
	return nullptr;
}
#undef GF
