/**************************************************************************/
/*  optest_gen.cpp                                                        */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// GENERATED by gds2cpp from res://opcode_tests.gd -- do not edit; regenerate.
#include "optest_gen.h"

#include "core/object/class_db.h"
#include "modules/gdscript/gdscript.h"
#include "modules/gdscript/gdscript_function.h"

// --- member slots ---
static constexpr int M_m_int = 0;
static constexpr int M_m_str = 1;
static constexpr int M_m_arr = 2;
static constexpr int M_m_dict = 3;

// ----------------------------------------------------------------------------
// func t_op_add(a: int, b: int) -> int: return a + b
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_add(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[5], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_op_add(a: int, b: int) -> int: return a + b
	gf->gds2cpp_operator_func(0)((&a_), (&b), (&t5));
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_arith(a: float, b: float) -> float: return a * b - a / b + fmod(a, b)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_arith(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[5], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[7], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[8], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	// func t_op_arith(a: float, b: float) -> float: return a * b - a / b + fmod(a, b)
	gf->gds2cpp_operator_func(0)((&a_), (&b), (&t7));
	gf->gds2cpp_operator_func(1)((&a_), (&b), (&t8));
	gf->gds2cpp_operator_func(2)((&t7), (&t8), (&t6));
	{
		const Variant *ca[] = { (&a_), (&b) };
		gf->gds2cpp_utility(0)((&t8), ca, 2);
	}
	gf->gds2cpp_operator_func(3)((&t6), (&t8), (&t5));
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_cmp(a: int, b: int) -> bool: return a < b and a <= b or a > b and a >= b
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_cmp(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[10];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[5], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[7], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[8], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[9], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	Variant &t9 = s[9]; // temp
	// func t_op_cmp(a: int, b: int) -> bool: return a < b and a <= b or a > b and a >= b
	gf->gds2cpp_operator_func(0)((&a_), (&b), (&t7));
	if (!bool(*(&t7))) {
		goto L22;
	}
	gf->gds2cpp_operator_func(1)((&a_), (&b), (&t8));
	if (!bool(*(&t8))) {
		goto L22;
	}
	*(&t6) = true;
	goto L24;
L22:;
	*(&t6) = false;
L24:;
	if (bool(*(&t6))) {
		goto L56;
	}
	gf->gds2cpp_operator_func(2)((&a_), (&b), (&t7));
	if (!bool(*(&t7))) {
		goto L47;
	}
	gf->gds2cpp_operator_func(3)((&a_), (&b), (&t9));
	if (!bool(*(&t9))) {
		goto L47;
	}
	*(&t8) = true;
	goto L49;
L47:;
	*(&t8) = false;
L49:;
	if (bool(*(&t8))) {
		goto L56;
	}
	*(&t5) = false;
	goto L58;
L56:;
	*(&t5) = true;
L58:;
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_eq(a, b) -> bool: return a == b or a != b
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_eq(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[8];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	// func t_op_eq(a, b) -> bool: return a == b or a != b
	{
		bool valid;
		Variant::evaluate((Variant::Operator)0, *(&a_), *(&b), *(&t6), valid);
	}
	if (bool(*(&t6))) {
		goto L30;
	}
	{
		bool valid;
		Variant::evaluate((Variant::Operator)1, *(&a_), *(&b), *(&t7), valid);
	}
	if (bool(*(&t7))) {
		goto L30;
	}
	*(&t5) = false;
	goto L32;
L30:;
	*(&t5) = true;
L32:;
	{
		const Variant *rr = (&t5);
		Variant::Type rt = (Variant::Type)1;
		if (rr->get_type() != rt) {
			Callable::CallError ce;
			Variant rv;
			if (Variant::can_convert_strict(rr->get_type(), rt)) {
				Variant::construct(rt, rv, &rr, 1, ce);
			} else {
				Variant::construct(rt, rv, nullptr, 0, ce);
			}
			return rv;
		}
		return *rr;
	}
	*(&t7) = Variant();
	*(&t6) = Variant();
	*(&t5) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_bit(a: int, b: int) -> int: return (a & b) | (a ^ b) << 1 >> 1
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_bit(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[10];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[5], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[7], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[8], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[9], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	Variant &t8 = s[8]; // temp
	Variant &t9 = s[9]; // temp
	// func t_op_bit(a: int, b: int) -> int: return (a & b) | (a ^ b) << 1 >> 1
	gf->gds2cpp_operator_func(0)((&a_), (&b), (&t6));
	gf->gds2cpp_operator_func(1)((&a_), (&b), (&t9));
	gf->gds2cpp_operator_func(2)((&t9), gf->gds2cpp_constant_ptr(0), (&t8));
	gf->gds2cpp_operator_func(3)((&t8), gf->gds2cpp_constant_ptr(0), (&t7));
	gf->gds2cpp_operator_func(4)((&t6), (&t7), (&t5));
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_not(a: bool) -> bool: return not a
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_not(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[4], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_op_not(a: bool) -> bool: return not a
	gf->gds2cpp_operator_func(0)((&a_), (&s[2]), (&t4));
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_neg(a: int) -> int: return -a
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_neg(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[4], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_op_neg(a: int) -> int: return -a
	gf->gds2cpp_operator_func(0)((&a_), (&s[2]), (&t4));
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_mod(a: int, b: int) -> int: return a % b
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_mod(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[5], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_op_mod(a: int, b: int) -> int: return a % b
	{
		bool valid;
		Variant::evaluate((Variant::Operator)12, *(&a_), *(&b), *(&t5), valid);
	}
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_in(a, arr: Array) -> bool: return a in arr
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_in(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &a_ = s[3]; // arg
	Variant &arr = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_op_in(a, arr: Array) -> bool: return a in arr
	{
		bool valid;
		Variant::evaluate((Variant::Operator)24, *(&a_), *(&arr), *(&t5), valid);
	}
	{
		const Variant *rr = (&t5);
		Variant::Type rt = (Variant::Type)1;
		if (rr->get_type() != rt) {
			Callable::CallError ce;
			Variant rv;
			if (Variant::can_convert_strict(rr->get_type(), rt)) {
				Variant::construct(rt, rv, &rr, 1, ce);
			} else {
				Variant::construct(rt, rv, nullptr, 0, ce);
			}
			return rv;
		}
		return *rr;
	}
	*(&t5) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_op_str_concat(a: String, b: String) -> String: return a + b
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_op_str_concat(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[5], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_op_str_concat(a: String, b: String) -> String: return a + b
	gf->gds2cpp_operator_func(0)((&a_), (&b), (&t5));
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_construct_vec2(x: float, y: float) -> Vector2: return Vector2(x, y)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_construct_vec2(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)5, s[5], nullptr, 0, _ce);
	}
	Variant &x = s[3]; // arg
	Variant &y = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_construct_vec2(x: float, y: float) -> Vector2: return Vector2(x, y)
	{
		const Variant *ca[] = { (&x), (&y) };
		gf->gds2cpp_constructor(0)((&t5), ca);
	}
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_construct_vec3(x: float, y: float, z: float) -> Vector3: return Vector3(x, y, z)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_construct_vec3(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[7];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 3 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)9, s[6], nullptr, 0, _ce);
	}
	Variant &x = s[3]; // arg
	Variant &y = s[4]; // arg
	Variant &z = s[5]; // arg
	Variant &t6 = s[6]; // temp
	// func t_construct_vec3(x: float, y: float, z: float) -> Vector3: return Vector3(x, y, z)
	{
		const Variant *ca[] = { (&x), (&y), (&z) };
		gf->gds2cpp_constructor(0)((&t6), ca);
	}
	return *(&t6);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_construct_color(r: float, g: float) -> Color: return Color(r, g, 0.0)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_construct_color(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)20, s[5], nullptr, 0, _ce);
	}
	Variant &r = s[3]; // arg
	Variant &g = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_construct_color(r: float, g: float) -> Color: return Color(r, g, 0.0)
	{
		const Variant *ca[] = { (&r), (&g), gf->gds2cpp_constant_ptr(0) };
		gf->gds2cpp_constructor(0)((&t5), ca);
	}
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_construct_array() -> Array: return [1, 2, 3, "four"]
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_construct_array(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &t3 = s[3]; // temp
	// func t_construct_array() -> Array: return [1, 2, 3, "four"]
	{
		Array a;
		a.resize(4);
		a[0] = *gf->gds2cpp_constant_ptr(0);
		a[1] = *gf->gds2cpp_constant_ptr(1);
		a[2] = *gf->gds2cpp_constant_ptr(2);
		a[3] = *gf->gds2cpp_constant_ptr(3);
		Variant *dd = (&t3);
		*dd = Variant();
		*dd = a;
	}
	return *(&t3);
	*(&t3) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_construct_dict() -> Dictionary: return {"x": 1, "y": 2}
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_construct_dict(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &t3 = s[3]; // temp
	// func t_construct_dict() -> Dictionary: return {"x": 1, "y": 2}
	{
		Dictionary d;
		d[*gf->gds2cpp_constant_ptr(0)] = *gf->gds2cpp_constant_ptr(1);
		d[*gf->gds2cpp_constant_ptr(2)] = *gf->gds2cpp_constant_ptr(3);
		Variant *dd = (&t3);
		*dd = Variant();
		*dd = d;
	}
	return *(&t3);
	*(&t3) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_typed_array() -> Array[int]: return [1, 2, 3]
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_typed_array(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	enum { GN__ = 0 }; // ""
	Variant &t3 = s[3]; // temp
	// func t_typed_array() -> Array[int]: return [1, 2, 3]
	{
		Array _arr;
		_arr.set_typed((uint32_t)2, gf->get_global_name(GN__), *gf->gds2cpp_constant_ptr(3));
		_arr.resize(3);
		_arr[0] = *gf->gds2cpp_constant_ptr(0);
		_arr[1] = *gf->gds2cpp_constant_ptr(1);
		_arr[2] = *gf->gds2cpp_constant_ptr(2);
		*(&t3) = _arr;
	}
	return *(&t3);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_typed_dict() -> Dictionary:
// 	var d: Dictionary = {}
// 	d[1] = "one"
// 	return d
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_typed_dict(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &d_ = s[3]; // local
	Variant &t4 = s[4]; // temp
	// var d: Dictionary = {}
	{
		Dictionary d;
		Variant *dd = (&t4);
		*dd = Variant();
		*dd = d;
	}
	*(&d_) = *(&t4);
	*(&t4) = Variant();
	// d[1] = "one"
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)((&d_), gf->gds2cpp_constant_ptr(1), gf->gds2cpp_constant_ptr(0), &valid);
	}
	// return d
	return *(&d_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_get_indexed(arr: Array, i: int): return arr[i]
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_get_indexed(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &arr = s[3]; // arg
	Variant &i_ = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_get_indexed(arr: Array, i: int): return arr[i]
	{
		bool valid;
		*(&t5) = (&arr)->get(*(&i_), &valid);
	}
	return *(&t5);
	*(&t5) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_set_indexed(arr: Array, i: int, v):
// 	arr[i] = v
// 	return arr
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_set_indexed(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 3 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &arr = s[3]; // arg
	Variant &i_ = s[4]; // arg
	Variant &v = s[5]; // arg
	// arr[i] = v
	{
		bool valid;
		(&arr)->set(*(&i_), *(&v), &valid);
	}
	// return arr
	return *(&arr);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_get_keyed(d: Dictionary, k): return d[k]
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_get_keyed(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &d_ = s[3]; // arg
	Variant &k = s[4]; // arg
	Variant &t5 = s[5]; // temp
	// func t_get_keyed(d: Dictionary, k): return d[k]
	{
		bool valid;
		gf->gds2cpp_keyed_getter(0)((&d_), (&k), (&t5), &valid);
	}
	return *(&t5);
	*(&t5) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_set_keyed(d: Dictionary, k, v):
// 	d[k] = v
// 	return d
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_set_keyed(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 3 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &d_ = s[3]; // arg
	Variant &k = s[4]; // arg
	Variant &v = s[5]; // arg
	// d[k] = v
	{
		bool valid;
		gf->gds2cpp_keyed_setter(0)((&d_), (&k), (&v), &valid);
	}
	// return d
	return *(&d_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_get_named(v: Vector2) -> float: return v.x
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_get_named(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[4], nullptr, 0, _ce);
	}
	Variant &v = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_get_named(v: Vector2) -> float: return v.x
	gf->gds2cpp_getter(0)((&v), (&t4));
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_set_named(v: Vector2, x: float) -> Vector2:
// 	v.x = x
// 	return v
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_set_named(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 2 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &v = s[3]; // arg
	Variant &x = s[4]; // arg
	// v.x = x
	gf->gds2cpp_setter(0)((&v), (&x));
	// return v
	return *(&v);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_get_member() -> int: return m_int
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_get_member(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[3];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	// func t_get_member() -> int: return m_int
	return *inst->gds2cpp_member_ptr(M_m_int);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_set_member(v: int) -> int:
// 	m_int = v
// 	return m_int
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_set_member(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &v = s[3]; // arg
	// m_int = v
	*inst->gds2cpp_member_ptr(M_m_int) = *(&v);
	// return m_int
	return *inst->gds2cpp_member_ptr(M_m_int);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_member_arr() -> Array: return m_arr
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_member_arr(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[3];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	// func t_member_arr() -> Array: return m_arr
	return *inst->gds2cpp_member_ptr(M_m_arr);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_member_dict_str() -> String: return m_str
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_member_dict_str(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[3];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	// func t_member_dict_str() -> String: return m_str
	return *inst->gds2cpp_member_ptr(M_m_str);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_cast_int(x) -> int: return x as int
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_cast_int(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[4], nullptr, 0, _ce);
	}
	Variant &x = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_cast_int(x) -> int: return x as int
	{
		const Variant *_s = (&x);
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, *(&t4), &_s, 1, _ce);
	}
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_cast_float(x) -> float: return x as float
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_cast_float(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[4], nullptr, 0, _ce);
	}
	Variant &x = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_cast_float(x) -> float: return x as float
	{
		const Variant *_s = (&x);
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, *(&t4), &_s, 1, _ce);
	}
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_cast_string(x) -> String: return str(x)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_cast_string(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[4], nullptr, 0, _ce);
	}
	enum { GN_str = 0 }; // "str"
	Variant &x = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_cast_string(x) -> String: return str(x)
	{
		const Variant *ca[] = { (&x) };
		Callable::CallError ce;
		Variant::call_utility_function(gf->get_global_name(GN_str), (&t4), ca, 1, ce);
	}
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_is_builtin(x) -> bool: return x is int
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_is_builtin(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[4], nullptr, 0, _ce);
	}
	Variant &x = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_is_builtin(x) -> bool: return x is int
	*(&t4) = ((&x)->get_type() == (Variant::Type)2);
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_is_array(x) -> bool: return x is Array
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_is_array(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[4], nullptr, 0, _ce);
	}
	Variant &x = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_is_array(x) -> bool: return x is Array
	*(&t4) = ((&x)->get_type() == (Variant::Type)28);
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_is_string(x) -> bool: return x is String
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_is_string(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[4], nullptr, 0, _ce);
	}
	Variant &x = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_is_string(x) -> bool: return x is String
	*(&t4) = ((&x)->get_type() == (Variant::Type)4);
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_if(a: int) -> String:
// 	if a > 10: return "big"
// 	elif a > 0: return "small"
// 	else: return "neg"
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_if(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[4], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// if a > 10: return "big"
	gf->gds2cpp_operator_func(0)((&a_), gf->gds2cpp_constant_ptr(0), (&t4));
	if (!bool(*(&t4))) {
		goto L16;
	}
	// if a > 10: return "big"
	return *gf->gds2cpp_constant_ptr(1);
	goto L36;
L16:;
	// elif a > 0: return "small"
	gf->gds2cpp_operator_func(0)((&a_), gf->gds2cpp_constant_ptr(2), (&t4));
	if (!bool(*(&t4))) {
		goto L32;
	}
	// elif a > 0: return "small"
	return *gf->gds2cpp_constant_ptr(3);
	goto L36;
L32:;
	// else: return "neg"
	return *gf->gds2cpp_constant_ptr(4);
L36:;
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_while(n: int) -> int:
// 	var s := 0
// 	var i := 0
// 	while i < n:
// 		s += i
// 		i += 1
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_while(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[8];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[7], nullptr, 0, _ce);
	}
	Variant &n = s[3]; // arg
	Variant &s_ = s[4]; // local
	Variant &i_ = s[5]; // local
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	// var s := 0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// var i := 0
	*(&i_) = *gf->gds2cpp_constant_ptr(0);
	// while i < n:
L12:;
	gf->gds2cpp_operator_func(0)((&i_), (&n), (&t6));
	if (!bool(*(&t6))) {
		goto L42;
	}
	// s += i
	gf->gds2cpp_operator_func(1)((&s_), (&i_), (&t7));
	*(&s_) = *(&t7);
	// i += 1
	gf->gds2cpp_operator_func(1)((&i_), gf->gds2cpp_constant_ptr(1), (&t7));
	*(&i_) = *(&t7);
	goto L12;
L42:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_ternary(a: int) -> String: return "yes" if a > 0 else "no"
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_ternary(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[4], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[5], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	// func t_ternary(a: int) -> String: return "yes" if a > 0 else "no"
	gf->gds2cpp_operator_func(0)((&a_), gf->gds2cpp_constant_ptr(0), (&t5));
	if (!bool(*(&t5))) {
		goto L15;
	}
	*(&t4) = *gf->gds2cpp_constant_ptr(1);
	goto L18;
L15:;
	*(&t4) = *gf->gds2cpp_constant_ptr(2);
L18:;
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_range(n: int) -> int:
// 	var s := 0
// 	for i in n: s += i
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_range(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[8], nullptr, 0, _ce);
	}
	Variant &n = s[3]; // arg
	Variant &s_ = s[4]; // local
	Variant &i_ = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	// var s := 0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// for i in n: s += i
	*(&_container_pos) = *(&n);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L34;
		}
		*(&i_) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L34;
		}
		*(&i_) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for i in n: s += i
	gf->gds2cpp_operator_func(0)((&s_), (&i_), (&t8));
	*(&s_) = *(&t8);
	goto L17;
L34:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_range3(a: int, b: int, c: int) -> int:
// 	var s := 0
// 	for i in range(a, b, c): s += i
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_range3(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[13];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 3 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[12], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &b = s[4]; // arg
	Variant &c = s[5]; // arg
	Variant &s_ = s[6]; // local
	Variant &i_ = s[7]; // local
	Variant &_counter_pos = s[8]; // local
	Variant &_range_from = s[9]; // local
	Variant &_range_to = s[10]; // local
	Variant &_range_step = s[11]; // local
	Variant &t12 = s[12]; // temp
	// var s := 0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// for i in range(a, b, c): s += i
	*(&_range_from) = *(&a_);
	*(&_range_to) = *(&b);
	*(&_range_step) = *(&c);
	{
		Variant *ctr = (&_counter_pos);
		int64_t _from = (int64_t)*(&_range_from);
		int64_t _to = (int64_t)*(&_range_to);
		int64_t _step = (int64_t)*(&_range_step);
		*ctr = _from;
		if (!(_from == _to ? false : (_from < _to ? _step > 0 : _step < 0))) {
			goto L43;
		}
		*(&i_) = _from;
	}
	goto L31;
L25:;
	{
		Variant *ctr = (&_counter_pos);
		int64_t _to = (int64_t)*(&_range_to);
		int64_t _step = (int64_t)*(&_range_step);
		int64_t _c = (int64_t)*ctr + _step;
		*ctr = _c;
		if ((_step < 0 && _c <= _to) || (_step > 0 && _c >= _to)) {
			goto L43;
		}
		*(&i_) = _c;
	}
L31:;
	// for i in range(a, b, c): s += i
	gf->gds2cpp_operator_func(0)((&s_), (&i_), (&t12));
	*(&s_) = *(&t12);
	goto L25;
L43:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_array(arr: Array) -> int:
// 	var s := 0
// 	for x in arr: s += int(x)
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_array(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[10];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[8], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[9], nullptr, 0, _ce);
	}
	Variant &arr = s[3]; // arg
	Variant &s_ = s[4]; // local
	Variant &x = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	Variant &t9 = s[9]; // temp
	// var s := 0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// for x in arr: s += int(x)
	*(&_container_pos) = *(&arr);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L40;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L40;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for x in arr: s += int(x)
	{
		const Variant *ca[] = { (&x) };
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, *(&t8), ca, 1, _ce);
	}
	gf->gds2cpp_operator_func(0)((&s_), (&t8), (&t9));
	*(&s_) = *(&t9);
	goto L17;
L40:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_int_array(arr: Array[int]) -> int:
// 	var s := 0
// 	for x in arr: s += x
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_int_array(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[8], nullptr, 0, _ce);
	}
	Variant &arr = s[3]; // arg
	Variant &s_ = s[4]; // local
	Variant &x = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	// var s := 0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// for x in arr: s += x
	*(&_container_pos) = *(&arr);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for x in arr: s += x
	gf->gds2cpp_operator_func(0)((&s_), (&x), (&t8));
	*(&s_) = *(&t8);
	goto L17;
L34:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_float(arr: Array[float]) -> float:
// 	var s := 0.0
// 	for x in arr: s += x
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_float(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[8], nullptr, 0, _ce);
	}
	Variant &arr = s[3]; // arg
	Variant &s_ = s[4]; // local
	Variant &x = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	// var s := 0.0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// for x in arr: s += x
	*(&_container_pos) = *(&arr);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for x in arr: s += x
	gf->gds2cpp_operator_func(0)((&s_), (&x), (&t8));
	*(&s_) = *(&t8);
	goto L17;
L34:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_string(s: String) -> int:
// 	var n := 0
// 	for c in s: n += 1
// 	return n
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_string(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[8], nullptr, 0, _ce);
	}
	Variant &s_ = s[3]; // arg
	Variant &n = s[4]; // local
	Variant &c = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	// var n := 0
	*(&n) = *gf->gds2cpp_constant_ptr(0);
	// for c in s: n += 1
	*(&_container_pos) = *(&s_);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L34;
		}
		*(&c) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L34;
		}
		*(&c) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for c in s: n += 1
	gf->gds2cpp_operator_func(0)((&n), gf->gds2cpp_constant_ptr(1), (&t8));
	*(&n) = *(&t8);
	goto L17;
L34:;
	// return n
	return *(&n);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_dict(d: Dictionary) -> Array:
// 	var keys := []
// 	for k in d: keys.append(k)
// 	return keys
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_dict(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	enum { GN_append = 0 }; // "append"
	Variant &d_ = s[3]; // arg
	Variant &keys = s[4]; // local
	Variant &k = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	// var keys := []
	{
		Array a;
		a.resize(0);
		Variant *dd = (&t8);
		*dd = Variant();
		*dd = a;
	}
	*(&keys) = *(&t8);
	*(&t8) = Variant();
	// for k in d: keys.append(k)
	*(&_container_pos) = *(&d_);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L41;
		}
		*(&k) = cont->iter_get(*ctr, valid);
	}
	goto L28;
L23:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L41;
		}
		*(&k) = cont->iter_get(*ctr, valid);
	}
L28:;
	// for k in d: keys.append(k)
	{
		const Variant *ca[] = { (&k) };
		Variant cret;
		Callable::CallError ce;
		(&keys)->callp(gf->get_global_name(GN_append), ca, 1, cret, ce);
	}
	*(&t8) = Variant();
	goto L23;
L41:;
	// return keys
	return *(&keys);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_packed_int(arr: PackedInt32Array) -> int:
// 	var s := 0
// 	for x in arr: s += x
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_packed_int(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[8], nullptr, 0, _ce);
	}
	Variant &arr = s[3]; // arg
	Variant &s_ = s[4]; // local
	Variant &x = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	// var s := 0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// for x in arr: s += x
	*(&_container_pos) = *(&arr);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for x in arr: s += x
	gf->gds2cpp_operator_func(0)((&s_), (&x), (&t8));
	*(&s_) = *(&t8);
	goto L17;
L34:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_packed_str(arr: PackedStringArray) -> String:
// 	var out := ""
// 	for x in arr: out += x
// 	return out
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_packed_str(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[9];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[8], nullptr, 0, _ce);
	}
	Variant &arr = s[3]; // arg
	Variant &out = s[4]; // local
	Variant &x = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	// var out := ""
	*(&out) = *gf->gds2cpp_constant_ptr(0);
	// for x in arr: out += x
	*(&_container_pos) = *(&arr);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L34;
		}
		*(&x) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for x in arr: out += x
	gf->gds2cpp_operator_func(0)((&out), (&x), (&t8));
	*(&out) = *(&t8);
	goto L17;
L34:;
	// return out
	return *(&out);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_for_vec2(arr: PackedVector2Array) -> float:
// 	var s := 0.0
// 	for v in arr: s += v.x
// 	return s
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_for_vec2(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[10];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[8], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[9], nullptr, 0, _ce);
	}
	Variant &arr = s[3]; // arg
	Variant &s_ = s[4]; // local
	Variant &v = s[5]; // local
	Variant &_counter_pos = s[6]; // local
	Variant &_container_pos = s[7]; // local
	Variant &t8 = s[8]; // temp
	Variant &t9 = s[9]; // temp
	// var s := 0.0
	*(&s_) = *gf->gds2cpp_constant_ptr(0);
	// for v in arr: s += v.x
	*(&_container_pos) = *(&arr);
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		*ctr = Variant();
		if (!cont->iter_init(*ctr, valid)) {
			goto L38;
		}
		*(&v) = cont->iter_get(*ctr, valid);
	}
	goto L22;
L17:;
	{
		Variant *ctr = (&_counter_pos);
		Variant *cont = (&_container_pos);
		bool valid;
		if (!cont->iter_next(*ctr, valid)) {
			goto L38;
		}
		*(&v) = cont->iter_get(*ctr, valid);
	}
L22:;
	// for v in arr: s += v.x
	gf->gds2cpp_getter(0)((&v), (&t8));
	gf->gds2cpp_operator_func(0)((&s_), (&t8), (&t9));
	*(&s_) = *(&t9);
	goto L17;
L38:;
	// return s
	return *(&s_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_call_utility(a: float) -> float: return abs(a) + sqrt(absf(a))
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_call_utility(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[8];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[6], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)3, s[7], nullptr, 0, _ce);
	}
	enum { GN_abs = 0 }; // "abs"
	Variant &a_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	Variant &t7 = s[7]; // temp
	// func t_call_utility(a: float) -> float: return abs(a) + sqrt(absf(a))
	{
		const Variant *ca[] = { (&a_) };
		Callable::CallError ce;
		Variant::call_utility_function(gf->get_global_name(GN_abs), (&t5), ca, 1, ce);
	}
	{
		const Variant *ca[] = { (&a_) };
		gf->gds2cpp_utility(0)((&t7), ca, 1);
	}
	{
		const Variant *ca[] = { (&t7) };
		gf->gds2cpp_utility(1)((&t6), ca, 1);
	}
	{
		bool valid;
		Variant::evaluate((Variant::Operator)6, *(&t5), *(&t6), *(&t4), valid);
	}
	{
		const Variant *rr = (&t4);
		Variant::Type rt = (Variant::Type)3;
		if (rr->get_type() != rt) {
			Callable::CallError ce;
			Variant rv;
			if (Variant::can_convert_strict(rr->get_type(), rt)) {
				Variant::construct(rt, rv, &rr, 1, ce);
			} else {
				Variant::construct(rt, rv, nullptr, 0, ce);
			}
			return rv;
		}
		return *rr;
	}
	*(&t5) = Variant();
	*(&t4) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_call_len(arr: Array) -> int: return len(arr)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_call_len(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[4], nullptr, 0, _ce);
	}
	Variant &arr = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_call_len(arr: Array) -> int: return len(arr)
	{
		const Variant *ca[] = { (&arr) };
		Callable::CallError _ce;
		gf->gds2cpp_gds_utility(0)((&t4), ca, 1, _ce);
	}
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_call_self(a: int) -> int: return t_op_add(a, 1)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_call_self(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[4], nullptr, 0, _ce);
	}
	enum { GN_t_op_add = 0 }; // "t_op_add"
	Variant &a_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// func t_call_self(a: int) -> int: return t_op_add(a, 1)
	{
		const Variant *ca[] = { (&a_), gf->gds2cpp_constant_ptr(0) };
		Variant cret;
		Callable::CallError ce;
		(&s[0])->callp(gf->get_global_name(GN_t_op_add), ca, 2, cret, ce);
		*(&t4) = cret;
	}
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_call_builtin_static() -> Color: return Color.from_hsv(0.5, 1.0, 1.0)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_call_builtin_static(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)20, s[3], nullptr, 0, _ce);
	}
	enum { GN_from_hsv = 0 }; // "from_hsv"
	Variant &t3 = s[3]; // temp
	// func t_call_builtin_static() -> Color: return Color.from_hsv(0.5, 1.0, 1.0)
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(0), gf->gds2cpp_constant_ptr(1), gf->gds2cpp_constant_ptr(1) };
		Callable::CallError _ce;
		Variant::call_static((Variant::Type)20, gf->get_global_name(GN_from_hsv), ca, 3, *(&t3), _ce);
	}
	return *(&t3);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_call_method(s: String) -> String: return s.to_upper().strip_edges()
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_call_method(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[4], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[5], nullptr, 0, _ce);
	}
	enum { GN_strip_edges = 0 }; // "strip_edges"
	Variant &s_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	// func t_call_method(s: String) -> String: return s.to_upper().strip_edges()
	{
		gf->gds2cpp_builtin_method(0)((&s_), nullptr, 0, (&t5));
	}
	{
		Variant cret;
		Callable::CallError ce;
		(&t5)->callp(gf->get_global_name(GN_strip_edges), nullptr, 0, cret, ce);
		*(&t4) = cret;
	}
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_ret_int() -> int: return 42
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_ret_int(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[3];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	// func t_ret_int() -> int: return 42
	return *gf->gds2cpp_constant_ptr(0);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_ret_array() -> Array[int]: return [9, 8, 7]
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_ret_array(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	enum { GN__ = 0 }; // ""
	Variant &t3 = s[3]; // temp
	// func t_ret_array() -> Array[int]: return [9, 8, 7]
	{
		Array _arr;
		_arr.set_typed((uint32_t)2, gf->get_global_name(GN__), *gf->gds2cpp_constant_ptr(3));
		_arr.resize(3);
		_arr[0] = *gf->gds2cpp_constant_ptr(0);
		_arr[1] = *gf->gds2cpp_constant_ptr(1);
		_arr[2] = *gf->gds2cpp_constant_ptr(2);
		*(&t3) = _arr;
	}
	return *(&t3);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_ret_dict() -> Dictionary: return {"k": "v"}
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_ret_dict(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	Variant &t3 = s[3]; // temp
	// func t_ret_dict() -> Dictionary: return {"k": "v"}
	{
		Dictionary d;
		d[*gf->gds2cpp_constant_ptr(0)] = *gf->gds2cpp_constant_ptr(1);
		Variant *dd = (&t3);
		*dd = Variant();
		*dd = d;
	}
	return *(&t3);
	*(&t3) = Variant();
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_assert(a: int) -> int:
// 	assert(a >= 0)
// 	return a * 2
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_assert(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[4], nullptr, 0, _ce);
	}
	Variant &a_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// assert(a >= 0)
	// return a * 2
	gf->gds2cpp_operator_func(0)((&a_), gf->gds2cpp_constant_ptr(0), (&t4));
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_string_ops(s: String) -> String:
// 	return s.substr(0, 1).to_upper() + s.substr(1)
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_string_ops(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[7];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[4], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[5], nullptr, 0, _ce);
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)4, s[6], nullptr, 0, _ce);
	}
	enum { GN_substr = 0 }; // "substr"
	Variant &s_ = s[3]; // arg
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	Variant &t6 = s[6]; // temp
	// return s.substr(0, 1).to_upper() + s.substr(1)
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(0), gf->gds2cpp_constant_ptr(1) };
		gf->gds2cpp_builtin_method(0)((&s_), ca, 2, (&t6));
	}
	{
		gf->gds2cpp_builtin_method(1)((&t6), nullptr, 0, (&t5));
	}
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(1) };
		Variant cret;
		Callable::CallError ce;
		(&s_)->callp(gf->get_global_name(GN_substr), ca, 1, cret, ce);
		*(&t6) = cret;
	}
	gf->gds2cpp_operator_func(0)((&t5), (&t6), (&t4));
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_static_get() -> int: return s_counter
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_static_get(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[4];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[3], nullptr, 0, _ce);
	}
	Variant &t3 = s[3]; // temp
	// func t_static_get() -> int: return s_counter
	*(&t3) = Object::cast_to<GDScript>(gf->gds2cpp_constant_ptr(0)->operator Object *())->gds2cpp_static_get(0);
	return *(&t3);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_static_set(v: int) -> int:
// 	s_counter = v
// 	return s_counter
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_static_set(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 1 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[4], nullptr, 0, _ce);
	}
	Variant &v = s[3]; // arg
	Variant &t4 = s[4]; // temp
	// s_counter = v
	*(&t4) = *(&v);
	Object::cast_to<GDScript>(gf->gds2cpp_constant_ptr(0)->operator Object *())->gds2cpp_static_set(0, *(&t4));
	// return s_counter
	*(&t4) = Object::cast_to<GDScript>(gf->gds2cpp_constant_ptr(0)->operator Object *())->gds2cpp_static_get(0);
	return *(&t4);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_typed_dict2() -> Dictionary:
// 	var d: Dictionary[int, String] = {1: "one", 2: "two"}
// 	return d
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_typed_dict2(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[5];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	enum { GN__ = 0 }; // ""
	Variant &d_ = s[3]; // local
	Variant &t4 = s[4]; // temp
	// var d: Dictionary[int, String] = {1: "one", 2: "two"}
	{
		Dictionary _d;
		_d.set_typed((uint32_t)2, gf->get_global_name(GN__), *gf->gds2cpp_constant_ptr(4), (uint32_t)4, gf->get_global_name(GN__), *gf->gds2cpp_constant_ptr(4));
		_d[*gf->gds2cpp_constant_ptr(0)] = *gf->gds2cpp_constant_ptr(1);
		_d[*gf->gds2cpp_constant_ptr(2)] = *gf->gds2cpp_constant_ptr(3);
		*(&t4) = _d;
	}
	*(&d_) = *(&t4);
	// return d
	return *(&d_);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_method_bind_validated() -> int:
// 	var r := RefCounted.new()
// 	return r.get_reference_count()
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_method_bind_validated(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)2, s[5], nullptr, 0, _ce);
	}
	enum { GN_new = 0 }; // "new"
	Variant &r = s[3]; // local
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	// var r := RefCounted.new()
	{
		Variant cret;
		Callable::CallError ce;
		gf->gds2cpp_constant_ptr(0)->callp(gf->get_global_name(GN_new), nullptr, 0, cret, ce);
		*(&t4) = cret;
	}
	*(&r) = *(&t4);
	*(&t4) = Variant();
	// return r.get_reference_count()
	{
		Object *_o = (&r)->operator Object *();
		Callable::CallError _ce;
		Variant _r = gf->gds2cpp_method(0)->call(_o, nullptr, 0, _ce);
		*(&t5) = _r;
	}
	return *(&t5);
	return Variant();
}

// ----------------------------------------------------------------------------
// func t_native_static() -> bool:
// 	var re := RegEx.create_from_string("[0-9]+")
// 	return re.is_valid()
// ----------------------------------------------------------------------------
Variant OpTest_gen::t_native_static(GDScriptInstance *inst, GDScriptFunction *gf, const Variant **p_args, int p_argc) {
	Variant s[6];
	s[0] = inst ? Variant(inst->get_owner()) : Variant();
	for (int i = 0; i < 0 && i < p_argc; i++) {
		s[3 + i] = *p_args[i];
	}
	{
		Callable::CallError _ce;
		Variant::construct((Variant::Type)1, s[5], nullptr, 0, _ce);
	}
	Variant &re = s[3]; // local
	Variant &t4 = s[4]; // temp
	Variant &t5 = s[5]; // temp
	// var re := RegEx.create_from_string("[0-9]+")
	{
		const Variant *ca[] = { gf->gds2cpp_constant_ptr(0) };
		Callable::CallError _ce;
		*(&t4) = gf->gds2cpp_method(0)->call(nullptr, ca, 1, _ce);
	}
	*(&re) = *(&t4);
	*(&t4) = Variant();
	// return re.is_valid()
	{
		Object *_o = (&re)->operator Object *();
		Callable::CallError _ce;
		Variant _r = gf->gds2cpp_method(1)->call(_o, nullptr, 0, _ce);
		*(&t5) = _r;
	}
	return *(&t5);
	return Variant();
}

OpTest_gen::Fn OpTest_gen::lookup(const StringName &p_name) {
	if (p_name == StringName("t_op_add")) {
		return &OpTest_gen::t_op_add;
	}
	if (p_name == StringName("t_op_arith")) {
		return &OpTest_gen::t_op_arith;
	}
	if (p_name == StringName("t_op_cmp")) {
		return &OpTest_gen::t_op_cmp;
	}
	if (p_name == StringName("t_op_eq")) {
		return &OpTest_gen::t_op_eq;
	}
	if (p_name == StringName("t_op_bit")) {
		return &OpTest_gen::t_op_bit;
	}
	if (p_name == StringName("t_op_not")) {
		return &OpTest_gen::t_op_not;
	}
	if (p_name == StringName("t_op_neg")) {
		return &OpTest_gen::t_op_neg;
	}
	if (p_name == StringName("t_op_mod")) {
		return &OpTest_gen::t_op_mod;
	}
	if (p_name == StringName("t_op_in")) {
		return &OpTest_gen::t_op_in;
	}
	if (p_name == StringName("t_op_str_concat")) {
		return &OpTest_gen::t_op_str_concat;
	}
	if (p_name == StringName("t_construct_vec2")) {
		return &OpTest_gen::t_construct_vec2;
	}
	if (p_name == StringName("t_construct_vec3")) {
		return &OpTest_gen::t_construct_vec3;
	}
	if (p_name == StringName("t_construct_color")) {
		return &OpTest_gen::t_construct_color;
	}
	if (p_name == StringName("t_construct_array")) {
		return &OpTest_gen::t_construct_array;
	}
	if (p_name == StringName("t_construct_dict")) {
		return &OpTest_gen::t_construct_dict;
	}
	if (p_name == StringName("t_typed_array")) {
		return &OpTest_gen::t_typed_array;
	}
	if (p_name == StringName("t_typed_dict")) {
		return &OpTest_gen::t_typed_dict;
	}
	if (p_name == StringName("t_get_indexed")) {
		return &OpTest_gen::t_get_indexed;
	}
	if (p_name == StringName("t_set_indexed")) {
		return &OpTest_gen::t_set_indexed;
	}
	if (p_name == StringName("t_get_keyed")) {
		return &OpTest_gen::t_get_keyed;
	}
	if (p_name == StringName("t_set_keyed")) {
		return &OpTest_gen::t_set_keyed;
	}
	if (p_name == StringName("t_get_named")) {
		return &OpTest_gen::t_get_named;
	}
	if (p_name == StringName("t_set_named")) {
		return &OpTest_gen::t_set_named;
	}
	if (p_name == StringName("t_get_member")) {
		return &OpTest_gen::t_get_member;
	}
	if (p_name == StringName("t_set_member")) {
		return &OpTest_gen::t_set_member;
	}
	if (p_name == StringName("t_member_arr")) {
		return &OpTest_gen::t_member_arr;
	}
	if (p_name == StringName("t_member_dict_str")) {
		return &OpTest_gen::t_member_dict_str;
	}
	if (p_name == StringName("t_cast_int")) {
		return &OpTest_gen::t_cast_int;
	}
	if (p_name == StringName("t_cast_float")) {
		return &OpTest_gen::t_cast_float;
	}
	if (p_name == StringName("t_cast_string")) {
		return &OpTest_gen::t_cast_string;
	}
	if (p_name == StringName("t_is_builtin")) {
		return &OpTest_gen::t_is_builtin;
	}
	if (p_name == StringName("t_is_array")) {
		return &OpTest_gen::t_is_array;
	}
	if (p_name == StringName("t_is_string")) {
		return &OpTest_gen::t_is_string;
	}
	if (p_name == StringName("t_if")) {
		return &OpTest_gen::t_if;
	}
	if (p_name == StringName("t_while")) {
		return &OpTest_gen::t_while;
	}
	if (p_name == StringName("t_ternary")) {
		return &OpTest_gen::t_ternary;
	}
	if (p_name == StringName("t_for_range")) {
		return &OpTest_gen::t_for_range;
	}
	if (p_name == StringName("t_for_range3")) {
		return &OpTest_gen::t_for_range3;
	}
	if (p_name == StringName("t_for_array")) {
		return &OpTest_gen::t_for_array;
	}
	if (p_name == StringName("t_for_int_array")) {
		return &OpTest_gen::t_for_int_array;
	}
	if (p_name == StringName("t_for_float")) {
		return &OpTest_gen::t_for_float;
	}
	if (p_name == StringName("t_for_string")) {
		return &OpTest_gen::t_for_string;
	}
	if (p_name == StringName("t_for_dict")) {
		return &OpTest_gen::t_for_dict;
	}
	if (p_name == StringName("t_for_packed_int")) {
		return &OpTest_gen::t_for_packed_int;
	}
	if (p_name == StringName("t_for_packed_str")) {
		return &OpTest_gen::t_for_packed_str;
	}
	if (p_name == StringName("t_for_vec2")) {
		return &OpTest_gen::t_for_vec2;
	}
	if (p_name == StringName("t_call_utility")) {
		return &OpTest_gen::t_call_utility;
	}
	if (p_name == StringName("t_call_len")) {
		return &OpTest_gen::t_call_len;
	}
	if (p_name == StringName("t_call_self")) {
		return &OpTest_gen::t_call_self;
	}
	if (p_name == StringName("t_call_builtin_static")) {
		return &OpTest_gen::t_call_builtin_static;
	}
	if (p_name == StringName("t_call_method")) {
		return &OpTest_gen::t_call_method;
	}
	if (p_name == StringName("t_ret_int")) {
		return &OpTest_gen::t_ret_int;
	}
	if (p_name == StringName("t_ret_array")) {
		return &OpTest_gen::t_ret_array;
	}
	if (p_name == StringName("t_ret_dict")) {
		return &OpTest_gen::t_ret_dict;
	}
	if (p_name == StringName("t_assert")) {
		return &OpTest_gen::t_assert;
	}
	if (p_name == StringName("t_string_ops")) {
		return &OpTest_gen::t_string_ops;
	}
	if (p_name == StringName("t_static_get")) {
		return &OpTest_gen::t_static_get;
	}
	if (p_name == StringName("t_static_set")) {
		return &OpTest_gen::t_static_set;
	}
	if (p_name == StringName("t_typed_dict2")) {
		return &OpTest_gen::t_typed_dict2;
	}
	if (p_name == StringName("t_method_bind_validated")) {
		return &OpTest_gen::t_method_bind_validated;
	}
	if (p_name == StringName("t_native_static")) {
		return &OpTest_gen::t_native_static;
	}
	return nullptr;
}
