/**************************************************************************/
/*  optest_gen.h                                                          */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#pragma once
// GENERATED by gds2cpp from res://opcode_tests.gd -- do not edit; regenerate.
#include "core/string/string_name.h"
#include "core/variant/variant.h"
class GDScriptInstance;
class GDScriptFunction;

struct OpTest_gen {
	typedef Variant (*Fn)(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Fn lookup(const StringName &p_name);
	static Variant fn_t_op_add(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_arith(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_cmp(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_eq(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_bit(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_not(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_neg(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_mod(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_in(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_op_str_concat(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_construct_vec2(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_construct_vec3(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_construct_color(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_construct_array(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_construct_dict(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_typed_array(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_typed_dict(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_get_indexed(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_set_indexed(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_get_keyed(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_set_keyed(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_get_named(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_set_named(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_get_member(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_set_member(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_member_arr(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_member_dict_str(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_cast_int(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_cast_float(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_cast_string(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_is_builtin(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_is_array(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_is_string(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_if(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_while(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_ternary(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_range(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_range3(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_array(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_int_array(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_float(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_string(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_dict(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_packed_int(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_packed_str(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_for_vec2(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_call_utility(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_call_len(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_call_self(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_call_builtin_static(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_call_method(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_ret_int(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_ret_array(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_ret_dict(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_assert(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_string_ops(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_static_get(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_static_set(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_typed_dict2(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_method_bind_validated(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
	static Variant fn_t_native_static(GDScriptInstance *, GDScriptFunction *, const Variant **, int);
};
